#!/bin/bash

if [ ! -f "./src/automotive/model/ASN1/currmode.txt" ]; then
    echo "Error. File ./src/automotive/model/ASN1/currmode.txt not found."

    exit 1
fi

currmode=$(head -n 1 "./src/automotive/model/ASN1/currmode.txt")


if [ "$currmode" == "v2" ]; then
    echo "Current versions (v2): CAM v1.4.1 and DENM v1.3.1"

    read -p "Do you want to switch to 'v1' (yes/no)? " yesno

    if [ "$yesno" == "yes" ]; then
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ActualNumberOfPassengers.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ActualNumberOfPassengers.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/AddRq.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/AddRq.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/AntennaOffsetSet.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/AntennaOffsetSet.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/AVIAEIIssuerIdentifier.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/AVIAEIIssuerIdentifier.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/BatteryStatus.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/BatteryStatus.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ChannelId.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ChannelId.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ChannelRq.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ChannelRq.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ChannelRs.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ChannelRs.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/CO2EmissionValue.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/CO2EmissionValue.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/Code-Units.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/Code-Units.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ContractAuthenticator.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ContractAuthenticator.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ContractSerialNumber.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ContractSerialNumber.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ContractValidity.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ContractValidity.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ContractVehicle.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ContractVehicle.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/CopyRq.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/CopyRq.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/CreditRq.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/CreditRq.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/CreditRs.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/CreditRs.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DateAndTime.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DateAndTime.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DateCompact.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DateCompact.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DDateTime.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DDateTime.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DDay.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DDay.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DDD-IO-LIST.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DDD-IO-LIST.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DebitRq.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DebitRq.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DebitRs.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DebitRs.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DescriptiveCharacteristics.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DescriptiveCharacteristics.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DestinationPlaces.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DestinationPlaces.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DestinationRoads.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DestinationRoads.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DHour.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DHour.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DigitalMap.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DigitalMap.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DMinute.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DMinute.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DMonth.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DMonth.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DOffset.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DOffset.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DYear.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/DYear.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/EFC-ContextMark.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/EFC-ContextMark.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/EFC-StationType.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/EFC-StationType.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ElevationConfidence.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ElevationConfidence.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/Engine.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/Engine.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/EquipmentOBUId.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/EquipmentOBUId.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/EquipmentStatus.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/EquipmentStatus.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ExceptionalCondition.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ExceptionalCondition.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/FuelType.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/FuelType.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/FullPositionVector.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/FullPositionVector.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/FutureCharacteristics.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/FutureCharacteristics.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GddAttribute.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GddAttribute.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GddAttributes.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GddAttributes.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GddStructure.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GddStructure.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GetInstanceRq.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GetInstanceRq.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GetInstanceRs.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GetInstanceRs.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GetStampedRq.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GetStampedRq.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GetStampedRs.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GetStampedRs.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GNSSstatus.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/GNSSstatus.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ICC-Id.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ICC-Id.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/Int3.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/Int3.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/Int4.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/Int4.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-applicablePeriod.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-applicablePeriod.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-applicableVehicleDimensions.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-applicableVehicleDimensions.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-destinationInformation.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-destinationInformation.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-directionalFlowOfLane.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-directionalFlowOfLane.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-distanceBetweenVehicles.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-distanceBetweenVehicles.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-exemptedApplicablePeriod.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-exemptedApplicablePeriod.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-numberOfLane.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-numberOfLane.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-rateOfIncline.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-rateOfIncline.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-section.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-section.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-speedLimits.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/InternationalSign-speedLimits.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/LaneAttributes-addGrpC.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/LaneAttributes-addGrpC.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/LPN.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/LPN.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/MovementEvent-addGrpC.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/MovementEvent-addGrpC.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/NodeAttributeSet-addGrpC.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/NodeAttributeSet-addGrpC.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/Node.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/Node.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/NodeITS.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/NodeITS.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/NodeLink.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/NodeLink.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/NumericString.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/NumericString.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/Offset-B09.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/Offset-B09.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/OpeningDaysHours.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/OpeningDaysHours.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PaymentFee.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PaymentFee.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PaymentMeansBalance.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PaymentMeansBalance.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PaymentMeans.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PaymentMeans.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PaymentMeansUnit.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PaymentMeansUnit.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PaymentSecurityData.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PaymentSecurityData.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PayUnit.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PayUnit.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PersonalAccountNumber.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PersonalAccountNumber.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PhoneNumber.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PhoneNumber.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PositionalAccuracy.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PositionalAccuracy.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PositionConfidence.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PositionConfidence.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PositionConfidenceSet.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PositionConfidenceSet.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PurseBalance.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/PurseBalance.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptAuthenticator.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptAuthenticator.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptContract.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptContract.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptData1.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptData1.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptData2.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptData2.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptData.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptData.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptDistance.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptDistance.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptFinancialPart.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptFinancialPart.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptICC-Id.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptICC-Id.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptOBUId.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptOBUId.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptServicePart.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptServicePart.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptServiceSerialNumber.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptServiceSerialNumber.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptText.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ReceiptText.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RejectedReason.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RejectedReason.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RepeatingPeriodDayTypes.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RepeatingPeriodDayTypes.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RequestorDescription-addGrpC.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RequestorDescription-addGrpC.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ResultFin.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ResultFin.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ResultOp.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ResultOp.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RTCMcorrections.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RTCMcorrections.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RTCMheader.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RTCMheader.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RTCMmessage.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RTCMmessage.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RTCMmessageList.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RTCMmessageList.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RTCM-Revision.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/RTCM-Revision.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SemiMajorAxisAccuracy.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SemiMajorAxisAccuracy.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SemiMajorAxisOrientation.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SemiMajorAxisOrientation.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SemiMinorAxisAccuracy.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SemiMinorAxisAccuracy.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SessionClass.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SessionClass.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SessionLocation.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SessionLocation.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SetInstanceRq.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SetInstanceRq.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SetMMIRq.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SetMMIRq.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SetStampedRq.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SetStampedRq.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SignedValue.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SignedValue.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SpeedandHeadingandThrottleConfidence.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SpeedandHeadingandThrottleConfidence.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SubRq.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/SubRq.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ThrottleConfidence.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ThrottleConfidence.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/TimeConfidence.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/TimeConfidence.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/TractorAxles.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/TractorAxles.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/TrailerAxles.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/TrailerAxles.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/TrailerDetails.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/TrailerDetails.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/TrailerLicencePlateNumber.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/TrailerLicencePlateNumber.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ValidityOfContract.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/ValidityOfContract.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleAuthenticator.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleAuthenticator.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleAxles.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleAxles.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleClass.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleClass.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleCurrentMaxTrainWeight.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleCurrentMaxTrainWeight.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleHeight.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleHeight.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleIdentificationNumber.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleIdentificationNumber.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleLicencePlateNumber.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleLicencePlateNumber.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleSpecificCharacteristics.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleSpecificCharacteristics.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleTotalDistance.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleTotalDistance.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleWeightLaden.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v2/VehicleWeightLaden.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt

        sed -i -E "s|(.*)#(model/ASN1/asn1-v2/EngineCharacteristics.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v2/EngineCharacteristics.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt

        sed -i -E "s|(.*)#(model/ASN1/asn1-v2/Control-addGrpC.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v2/Control-addGrpC.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v2/IssuerIdentifier.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v2/IssuerIdentifier.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v2/MessageFrame.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v2/MessageFrame.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt

        sed -i -E "s/(.*)asn1-v2(.*)/\1asn1-v1\2/g" ./src/automotive/CMakeLists.txt

        sed -i -E "s|(.*)(asn1cpp::setField\(closedLanes->outerhardShoulderStatus.*)|\1//\2|g" ./src/automotive/model/Facilities/denBasicService.cc
        sed -i -E "s|(.*)(auto outerHand = asn1cpp::getField\(closedLanes->outerhardShoulderStatus.*)|\1//\2|g" ./src/automotive/model/Facilities/denBasicService.cc
        sed -i -E "s|(.*)(roadworks_data.outerhardShoulderStatus.setData.*)|\1//\2|g" ./src/automotive/model/Facilities/denBasicService.cc

        echo "v1" > ./src/automotive/model/ASN1/currmode.txt

        echo "Successfully switched to: 'v1' (CAM v1.3.2 and DENM v1.2.2)"
    elif [ "$yesno" == "no" ]; then
        echo "Operation aborted."
    else
        echo "Error: $yesno is not a valid answer."
        echo "Operation aborted."
    fi
elif [ "$currmode" == "v1" ]; then
    echo "Current versions (v1): CAM v1.3.2 and DENM v1.2.2"

    read -p "Do you want to switch to 'v2' (yes/no)? " yesno

    if [ "$yesno" == "yes" ]; then
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ActualNumberOfPassengers.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ActualNumberOfPassengers.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/AddRq.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/AddRq.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/AntennaOffsetSet.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/AntennaOffsetSet.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/AVIAEIIssuerIdentifier.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/AVIAEIIssuerIdentifier.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/BatteryStatus.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/BatteryStatus.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ChannelId.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ChannelId.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ChannelRq.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ChannelRq.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ChannelRs.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ChannelRs.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/CO2EmissionValue.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/CO2EmissionValue.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/Code-Units.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/Code-Units.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ContractAuthenticator.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ContractAuthenticator.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ContractSerialNumber.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ContractSerialNumber.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ContractValidity.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ContractValidity.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ContractVehicle.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ContractVehicle.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/CopyRq.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/CopyRq.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/CreditRq.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/CreditRq.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/CreditRs.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/CreditRs.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DateAndTime.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DateAndTime.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DateCompact.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DateCompact.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DDateTime.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DDateTime.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DDay.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DDay.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DDD-IO-LIST.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DDD-IO-LIST.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DebitRq.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DebitRq.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DebitRs.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DebitRs.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DescriptiveCharacteristics.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DescriptiveCharacteristics.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DestinationPlaces.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DestinationPlaces.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DestinationRoads.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DestinationRoads.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DHour.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DHour.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DigitalMap.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DigitalMap.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DMinute.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DMinute.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DMonth.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DMonth.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DOffset.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DOffset.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DYear.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/DYear.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/EFC-ContextMark.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/EFC-ContextMark.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/EFC-StationType.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/EFC-StationType.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ElevationConfidence.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ElevationConfidence.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/Engine.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/Engine.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/EquipmentOBUId.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/EquipmentOBUId.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/EquipmentStatus.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/EquipmentStatus.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ExceptionalCondition.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ExceptionalCondition.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/FuelType.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/FuelType.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/FullPositionVector.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/FullPositionVector.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/FutureCharacteristics.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/FutureCharacteristics.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GddAttribute.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GddAttribute.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GddAttributes.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GddAttributes.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GddStructure.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GddStructure.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GetInstanceRq.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GetInstanceRq.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GetInstanceRs.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GetInstanceRs.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GetStampedRq.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GetStampedRq.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GetStampedRs.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GetStampedRs.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GNSSstatus.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/GNSSstatus.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ICC-Id.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ICC-Id.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/Int3.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/Int3.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/Int4.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/Int4.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-applicablePeriod.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-applicablePeriod.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-applicableVehicleDimensions.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-applicableVehicleDimensions.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-destinationInformation.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-destinationInformation.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-directionalFlowOfLane.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-directionalFlowOfLane.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-distanceBetweenVehicles.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-distanceBetweenVehicles.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-exemptedApplicablePeriod.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-exemptedApplicablePeriod.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-numberOfLane.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-numberOfLane.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-rateOfIncline.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-rateOfIncline.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-section.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-section.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-speedLimits.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/InternationalSign-speedLimits.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ISO14823Attribute.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ISO14823Attribute.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ISO14823AttributesMember.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ISO14823AttributesMember.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/LaneAttributes-addGrpC.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/LaneAttributes-addGrpC.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/LPN.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/LPN.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/MovementEvent-addGrpC.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/MovementEvent-addGrpC.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/NodeAttributeSet-addGrpC.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/NodeAttributeSet-addGrpC.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/Node.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/Node.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/NodeITS.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/NodeITS.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/NodeLink.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/NodeLink.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/NumericString.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/NumericString.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/Offset-B09.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/Offset-B09.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/OpeningDaysHours.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/OpeningDaysHours.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PaymentFee.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PaymentFee.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PaymentMeansBalance.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PaymentMeansBalance.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PaymentMeans.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PaymentMeans.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PaymentMeansUnit.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PaymentMeansUnit.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PaymentSecurityData.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PaymentSecurityData.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PayUnit.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PayUnit.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PersonalAccountNumber.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PersonalAccountNumber.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PhoneNumber.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PhoneNumber.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PositionalAccuracy.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PositionalAccuracy.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PositionConfidence.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PositionConfidence.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PositionConfidenceSet.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PositionConfidenceSet.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PurseBalance.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/PurseBalance.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptAuthenticator.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptAuthenticator.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptContract.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptContract.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptData1.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptData1.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptData2.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptData2.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptData.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptData.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptDistance.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptDistance.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptFinancialPart.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptFinancialPart.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptICC-Id.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptICC-Id.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptOBUId.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptOBUId.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptServicePart.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptServicePart.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptServiceSerialNumber.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptServiceSerialNumber.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptText.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ReceiptText.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RejectedReason.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RejectedReason.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RepeatingPeriodDayTypes.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RepeatingPeriodDayTypes.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RequestorDescription-addGrpC.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RequestorDescription-addGrpC.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ResultFin.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ResultFin.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ResultOp.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ResultOp.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RTCMcorrections.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RTCMcorrections.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RTCMheader.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RTCMheader.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RTCMmessage.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RTCMmessage.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RTCMmessageList.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RTCMmessageList.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RTCM-Revision.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/RTCM-Revision.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SemiMajorAxisAccuracy.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SemiMajorAxisAccuracy.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SemiMajorAxisOrientation.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SemiMajorAxisOrientation.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SemiMinorAxisAccuracy.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SemiMinorAxisAccuracy.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SessionClass.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SessionClass.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SessionLocation.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SessionLocation.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SetInstanceRq.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SetInstanceRq.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SetMMIRq.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SetMMIRq.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SetStampedRq.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SetStampedRq.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SignedValue.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SignedValue.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SpeedandHeadingandThrottleConfidence.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SpeedandHeadingandThrottleConfidence.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SubRq.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/SubRq.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ThrottleConfidence.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ThrottleConfidence.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/TimeConfidence.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/TimeConfidence.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/TractorAxles.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/TractorAxles.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/TrailerAxles.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/TrailerAxles.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/TrailerDetails.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/TrailerDetails.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/TrailerLicencePlateNumber.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/TrailerLicencePlateNumber.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ValidityOfContract.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/ValidityOfContract.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleAuthenticator.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleAuthenticator.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleAxles.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleAxles.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleClass.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleClass.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleCurrentMaxTrainWeight.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleCurrentMaxTrainWeight.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleHeight.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleHeight.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleIdentificationNumber.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleIdentificationNumber.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleLicencePlateNumber.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleLicencePlateNumber.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleSpecificCharacteristics.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleSpecificCharacteristics.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleTotalDistance.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleTotalDistance.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleWeightLaden.c.*)|\1\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)#(model/ASN1/asn1-v1/VehicleWeightLaden.h.*)|\1\2|g" ./src/automotive/CMakeLists.txt

        sed -i -E "s|(.*)(model/ASN1/asn1-v1/Control-addGrpC.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v1/Control-addGrpC.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v1/IssuerIdentifier.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v1/IssuerIdentifier.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v1/MessageFrame.c.*)|\1#\2|g" ./src/automotive/CMakeLists.txt
        sed -i -E "s|(.*)(model/ASN1/asn1-v1/MessageFrame.h.*)|\1#\2|g" ./src/automotive/CMakeLists.txt

        sed -i -E "s/(.*)asn1-v1(.*)/\1asn1-v2\2/g" ./src/automotive/CMakeLists.txt

        sed -i -E "s|(.*)//(asn1cpp::setField\(closedLanes->outerhardShoulderStatus.*)|\1\2|g" ./src/automotive/model/Facilities/denBasicService.cc
        sed -i -E "s|(.*)//(auto outerHand = asn1cpp::getField\(closedLanes->outerhardShoulderStatus.*)|\1\2|g" ./src/automotive/model/Facilities/denBasicService.cc
        sed -i -E "s|(.*)//(roadworks_data.outerhardShoulderStatus.setData.*)|\1\2|g" ./src/automotive/model/Facilities/denBasicService.cc

        echo "v2" > ./src/automotive/model/ASN1/currmode.txt

        echo "Successfully switched to: 'v2' (CAM v1.4.1 and DENM v1.3.1)"
    elif [ "$yesno" == "no" ]; then
        echo "Operation aborted."
    else
        echo "Error: $yesno is not a valid answer."
        echo "Operation aborted."
    fi
else
    echo "Error. File ./src/automotive/currmode.txt seems to be corrupted."

    exit 1
fi