# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('vehicle-visualizer', ['core'])
    module.source = [
        'model/vehicle-visualizer.cc',
        ]

    module_test = bld.create_ns3_module_test_library('vehicle-visualizer')
    module_test.source = [
        'test/vehicle-visualizer-test-suite.cc',
        ]

    headers = bld(features='ns3header')
    headers.module = 'vehicle-visualizer'
    headers.source = [
        'model/vehicle-visualizer.h',
        ]

    # if bld.env.ENABLE_EXAMPLES:
    #    bld.recurse('examples')

    # bld.ns3_python_bindings()

