# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('gps-tc-example', ['gps-tc','visualizer'])
    obj.source = 'gps-tc-example.cc'

