/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_AdverseWeatherCondition_VisibilitySubCauseCodeV1_H_
#define	_AdverseWeatherCondition_VisibilitySubCauseCodeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AdverseWeatherCondition_VisibilitySubCauseCodeV1 {
	AdverseWeatherCondition_VisibilitySubCauseCodeV1_unavailable	= 0,
	AdverseWeatherCondition_VisibilitySubCauseCodeV1_fog	= 1,
	AdverseWeatherCondition_VisibilitySubCauseCodeV1_smoke	= 2,
	AdverseWeatherCondition_VisibilitySubCauseCodeV1_heavySnowfall	= 3,
	AdverseWeatherCondition_VisibilitySubCauseCodeV1_heavyRain	= 4,
	AdverseWeatherCondition_VisibilitySubCauseCodeV1_heavyHail	= 5,
	AdverseWeatherCondition_VisibilitySubCauseCodeV1_lowSunGlare	= 6,
	AdverseWeatherCondition_VisibilitySubCauseCodeV1_sandstorms	= 7,
	AdverseWeatherCondition_VisibilitySubCauseCodeV1_swarmsOfInsects	= 8
} e_AdverseWeatherCondition_VisibilitySubCauseCodeV1;

/* AdverseWeatherCondition-VisibilitySubCauseCodeV1 */
typedef long	 AdverseWeatherCondition_VisibilitySubCauseCodeV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AdverseWeatherCondition_VisibilitySubCauseCodeV1;
asn_struct_free_f AdverseWeatherCondition_VisibilitySubCauseCodeV1_free;
asn_struct_print_f AdverseWeatherCondition_VisibilitySubCauseCodeV1_print;
asn_constr_check_f AdverseWeatherCondition_VisibilitySubCauseCodeV1_constraint;
ber_type_decoder_f AdverseWeatherCondition_VisibilitySubCauseCodeV1_decode_ber;
der_type_encoder_f AdverseWeatherCondition_VisibilitySubCauseCodeV1_encode_der;
xer_type_decoder_f AdverseWeatherCondition_VisibilitySubCauseCodeV1_decode_xer;
xer_type_encoder_f AdverseWeatherCondition_VisibilitySubCauseCodeV1_encode_xer;
oer_type_decoder_f AdverseWeatherCondition_VisibilitySubCauseCodeV1_decode_oer;
oer_type_encoder_f AdverseWeatherCondition_VisibilitySubCauseCodeV1_encode_oer;
per_type_decoder_f AdverseWeatherCondition_VisibilitySubCauseCodeV1_decode_uper;
per_type_encoder_f AdverseWeatherCondition_VisibilitySubCauseCodeV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AdverseWeatherCondition_VisibilitySubCauseCodeV1_H_ */
#include "asn_internal.h"
