/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_CollectivePerceptionMessageV1_H_
#define	_CollectivePerceptionMessageV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GenerationDeltaTime.h"
#include "CpmParametersV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CollectivePerceptionMessageV1 */
typedef struct CollectivePerceptionMessageV1 {
	GenerationDeltaTime_t	 generationDeltaTime;
	CpmParametersV1_t	 cpmParameters;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CollectivePerceptionMessageV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CollectivePerceptionMessageV1;
extern asn_SEQUENCE_specifics_t asn_SPC_CollectivePerceptionMessageV1_specs_1;
extern asn_TYPE_member_t asn_MBR_CollectivePerceptionMessageV1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CollectivePerceptionMessageV1_H_ */
#include "asn_internal.h"
