/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-C-ITS/CAM-PDU-Descriptions-1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "CoopAwarenessV1.h"

asn_TYPE_member_t asn_MBR_CoopAwarenessV1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CoopAwarenessV1, generationDeltaTime),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GenerationDeltaTimeV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"generationDeltaTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CoopAwarenessV1, camParameters),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CamParametersV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"camParameters"
		},
};
static const ber_tlv_tag_t asn_DEF_CoopAwarenessV1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CoopAwarenessV1_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* generationDeltaTime */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* camParameters */
};
asn_SEQUENCE_specifics_t asn_SPC_CoopAwarenessV1_specs_1 = {
	sizeof(struct CoopAwarenessV1),
	offsetof(struct CoopAwarenessV1, _asn_ctx),
	asn_MAP_CoopAwarenessV1_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CoopAwarenessV1 = {
	"CoopAwarenessV1",
	"CoopAwarenessV1",
	&asn_OP_SEQUENCE,
	asn_DEF_CoopAwarenessV1_tags_1,
	sizeof(asn_DEF_CoopAwarenessV1_tags_1)
		/sizeof(asn_DEF_CoopAwarenessV1_tags_1[0]), /* 1 */
	asn_DEF_CoopAwarenessV1_tags_1,	/* Same as above */
	sizeof(asn_DEF_CoopAwarenessV1_tags_1)
		/sizeof(asn_DEF_CoopAwarenessV1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CoopAwarenessV1_1,
	2,	/* Elements count */
	&asn_SPC_CoopAwarenessV1_specs_1	/* Additional specs */
};

