/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_CurvatureCalculationModeV1_H_
#define	_CurvatureCalculationModeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CurvatureCalculationModeV1 {
	CurvatureCalculationModeV1_yawRateUsed	= 0,
	CurvatureCalculationModeV1_yawRateNotUsed	= 1,
	CurvatureCalculationModeV1_unavailable	= 2
	/*
	 * Enumeration is extensible
	 */
} e_CurvatureCalculationModeV1;

/* CurvatureCalculationModeV1 */
typedef long	 CurvatureCalculationModeV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CurvatureCalculationModeV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CurvatureCalculationModeV1;
extern const asn_INTEGER_specifics_t asn_SPC_CurvatureCalculationModeV1_specs_1;
asn_struct_free_f CurvatureCalculationModeV1_free;
asn_struct_print_f CurvatureCalculationModeV1_print;
asn_constr_check_f CurvatureCalculationModeV1_constraint;
ber_type_decoder_f CurvatureCalculationModeV1_decode_ber;
der_type_encoder_f CurvatureCalculationModeV1_encode_der;
xer_type_decoder_f CurvatureCalculationModeV1_decode_xer;
xer_type_encoder_f CurvatureCalculationModeV1_encode_xer;
oer_type_decoder_f CurvatureCalculationModeV1_decode_oer;
oer_type_encoder_f CurvatureCalculationModeV1_encode_oer;
per_type_decoder_f CurvatureCalculationModeV1_decode_uper;
per_type_encoder_f CurvatureCalculationModeV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CurvatureCalculationModeV1_H_ */
#include "asn_internal.h"
