/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_CurvatureConfidenceV1_H_
#define	_CurvatureConfidenceV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CurvatureConfidenceV1 {
	CurvatureConfidenceV1_onePerMeter_0_00002	= 0,
	CurvatureConfidenceV1_onePerMeter_0_0001	= 1,
	CurvatureConfidenceV1_onePerMeter_0_0005	= 2,
	CurvatureConfidenceV1_onePerMeter_0_002	= 3,
	CurvatureConfidenceV1_onePerMeter_0_01	= 4,
	CurvatureConfidenceV1_onePerMeter_0_1	= 5,
	CurvatureConfidenceV1_outOfRange	= 6,
	CurvatureConfidenceV1_unavailable	= 7
} e_CurvatureConfidenceV1;

/* CurvatureConfidenceV1 */
typedef long	 CurvatureConfidenceV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_CurvatureConfidenceV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_CurvatureConfidenceV1;
extern const asn_INTEGER_specifics_t asn_SPC_CurvatureConfidenceV1_specs_1;
asn_struct_free_f CurvatureConfidenceV1_free;
asn_struct_print_f CurvatureConfidenceV1_print;
asn_constr_check_f CurvatureConfidenceV1_constraint;
ber_type_decoder_f CurvatureConfidenceV1_decode_ber;
der_type_encoder_f CurvatureConfidenceV1_encode_der;
xer_type_decoder_f CurvatureConfidenceV1_decode_xer;
xer_type_encoder_f CurvatureConfidenceV1_encode_xer;
oer_type_decoder_f CurvatureConfidenceV1_decode_oer;
oer_type_encoder_f CurvatureConfidenceV1_encode_oer;
per_type_decoder_f CurvatureConfidenceV1_decode_uper;
per_type_encoder_f CurvatureConfidenceV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _CurvatureConfidenceV1_H_ */
#include "asn_internal.h"
