/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_EquipmentStatus_H_
#define	_EquipmentStatus_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EquipmentStatus */
typedef BIT_STRING_t	 EquipmentStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EquipmentStatus;
asn_struct_free_f EquipmentStatus_free;
asn_struct_print_f EquipmentStatus_print;
asn_constr_check_f EquipmentStatus_constraint;
ber_type_decoder_f EquipmentStatus_decode_ber;
der_type_encoder_f EquipmentStatus_encode_der;
xer_type_decoder_f EquipmentStatus_decode_xer;
xer_type_encoder_f EquipmentStatus_encode_xer;
oer_type_decoder_f EquipmentStatus_decode_oer;
oer_type_encoder_f EquipmentStatus_encode_oer;
per_type_decoder_f EquipmentStatus_decode_uper;
per_type_encoder_f EquipmentStatus_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EquipmentStatus_H_ */
#include "asn_internal.h"
