/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103097Module"
 * 	found in "EtsiTs103097Module.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_v2_1_1/`
 */

#ifndef	_EtsiTs103097Data_SignedAndEncrypted_Unicast_H_
#define	_EtsiTs103097Data_SignedAndEncrypted_Unicast_H_


#include "asn_application.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _EtsiTs103097Data_SignedAndEncrypted_Unicast_H_ */
#include "asn_internal.h"
