/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103097ExtensionModule"
 * 	found in "EtsiTs103097ExtensionModule.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_v2_1_1/`
 */

#ifndef	_EtsiTs102941DeltaCtlRequest_H_
#define	_EtsiTs102941DeltaCtlRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "EtsiTs102941CtlRequest.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EtsiTs102941DeltaCtlRequest */
typedef EtsiTs102941CtlRequest_t	 EtsiTs102941DeltaCtlRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EtsiTs102941DeltaCtlRequest;
asn_struct_free_f EtsiTs102941DeltaCtlRequest_free;
asn_struct_print_f EtsiTs102941DeltaCtlRequest_print;
asn_constr_check_f EtsiTs102941DeltaCtlRequest_constraint;
ber_type_decoder_f EtsiTs102941DeltaCtlRequest_decode_ber;
der_type_encoder_f EtsiTs102941DeltaCtlRequest_encode_der;
xer_type_decoder_f EtsiTs102941DeltaCtlRequest_decode_xer;
xer_type_encoder_f EtsiTs102941DeltaCtlRequest_encode_xer;
jer_type_encoder_f EtsiTs102941DeltaCtlRequest_encode_jer;
oer_type_decoder_f EtsiTs102941DeltaCtlRequest_decode_oer;
oer_type_encoder_f EtsiTs102941DeltaCtlRequest_encode_oer;
per_type_decoder_f EtsiTs102941DeltaCtlRequest_decode_uper;
per_type_encoder_f EtsiTs102941DeltaCtlRequest_encode_uper;
per_type_decoder_f EtsiTs102941DeltaCtlRequest_decode_aper;
per_type_encoder_f EtsiTs102941DeltaCtlRequest_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _EtsiTs102941DeltaCtlRequest_H_ */
#include "asn_internal.h"
