/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EtsiTs103097ExtensionModule"
 * 	found in "EtsiTs103097ExtensionModule.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_v2_1_1/`
 */

#ifndef	_EtsiTs102941CtlRequest_H_
#define	_EtsiTs102941CtlRequest_H_


#include "asn_application.h"

/* Including external dependencies */
#include "HashedId8.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EtsiTs102941CtlRequest */
typedef struct EtsiTs102941CtlRequest {
	HashedId8_t	 issuerId;
	long	*lastKnownCtlSequence;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EtsiTs102941CtlRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EtsiTs102941CtlRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_EtsiTs102941CtlRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_EtsiTs102941CtlRequest_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EtsiTs102941CtlRequest_H_ */
#include "asn_internal.h"
