/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_FreeSpaceConfidenceV1_H_
#define	_FreeSpaceConfidenceV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum FreeSpaceConfidenceV1 {
	FreeSpaceConfidenceV1_unknown	= 0,
	FreeSpaceConfidenceV1_onePercent	= 1,
	FreeSpaceConfidenceV1_oneHundredPercent	= 100,
	FreeSpaceConfidenceV1_unavailable	= 101
} e_FreeSpaceConfidenceV1;

/* FreeSpaceConfidenceV1 */
typedef long	 FreeSpaceConfidenceV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_FreeSpaceConfidenceV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_FreeSpaceConfidenceV1;
asn_struct_free_f FreeSpaceConfidenceV1_free;
asn_struct_print_f FreeSpaceConfidenceV1_print;
asn_constr_check_f FreeSpaceConfidenceV1_constraint;
ber_type_decoder_f FreeSpaceConfidenceV1_decode_ber;
der_type_encoder_f FreeSpaceConfidenceV1_encode_der;
xer_type_decoder_f FreeSpaceConfidenceV1_decode_xer;
xer_type_encoder_f FreeSpaceConfidenceV1_encode_xer;
oer_type_decoder_f FreeSpaceConfidenceV1_decode_oer;
oer_type_encoder_f FreeSpaceConfidenceV1_encode_oer;
per_type_decoder_f FreeSpaceConfidenceV1_decode_uper;
per_type_encoder_f FreeSpaceConfidenceV1_encode_uper;
per_type_decoder_f FreeSpaceConfidenceV1_decode_aper;
per_type_encoder_f FreeSpaceConfidenceV1_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _FreeSpaceConfidenceV1_H_ */
#include "asn_internal.h"
