/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot2BaseTypes"
 * 	found in "Ieee1609Dot2BaseTypes.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -D output_v2_1_1/`
 */

#ifndef	_GroupLinkageValue_H_
#define	_GroupLinkageValue_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GroupLinkageValue */
typedef struct GroupLinkageValue {
	OCTET_STRING_t	 jValue;
	OCTET_STRING_t	 value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GroupLinkageValue_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GroupLinkageValue;
extern asn_SEQUENCE_specifics_t asn_SPC_GroupLinkageValue_specs_1;
extern asn_TYPE_member_t asn_MBR_GroupLinkageValue_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _GroupLinkageValue_H_ */
#include "asn_internal.h"
