/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-base.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_IntermediatePoint_H_
#define	_IntermediatePoint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IntermediatePointReference.h"
#include "IntermediatePointLane.h"
#include "IntermediatePointIntersection.h"
#include "IntermediatePointOffroad.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum IntermediatePoint_PR {
	IntermediatePoint_PR_NOTHING,	/* No components present */
	IntermediatePoint_PR_reference,
	IntermediatePoint_PR_lane,
	IntermediatePoint_PR_intersection,
	IntermediatePoint_PR_offroad
} IntermediatePoint_PR;

/* IntermediatePoint */
typedef struct IntermediatePoint {
	IntermediatePoint_PR present;
	union IntermediatePoint_u {
		IntermediatePointReference_t	 reference;
		IntermediatePointLane_t	 lane;
		IntermediatePointIntersection_t	 intersection;
		IntermediatePointOffroad_t	 offroad;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IntermediatePoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IntermediatePoint;
extern asn_CHOICE_specifics_t asn_SPC_IntermediatePoint_specs_1;
extern asn_TYPE_member_t asn_MBR_IntermediatePoint_1[4];
extern asn_per_constraints_t asn_PER_type_IntermediatePoint_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _IntermediatePoint_H_ */
#include "asn_internal.h"
