/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VAM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-C-ITS/VAM-PDU-Descriptions.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ItsPduHeaderVam_H_
#define	_ItsPduHeaderVam_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ItsPduHeader.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ItsPduHeaderVam */
typedef ItsPduHeader_t	 ItsPduHeaderVam_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ItsPduHeaderVam_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ItsPduHeaderVam;
asn_struct_free_f ItsPduHeaderVam_free;
asn_struct_print_f ItsPduHeaderVam_print;
asn_constr_check_f ItsPduHeaderVam_constraint;
ber_type_decoder_f ItsPduHeaderVam_decode_ber;
der_type_encoder_f ItsPduHeaderVam_encode_der;
xer_type_decoder_f ItsPduHeaderVam_decode_xer;
xer_type_encoder_f ItsPduHeaderVam_encode_xer;
oer_type_decoder_f ItsPduHeaderVam_decode_oer;
oer_type_encoder_f ItsPduHeaderVam_encode_oer;
per_type_decoder_f ItsPduHeaderVam_decode_uper;
per_type_encoder_f ItsPduHeaderVam_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ItsPduHeaderVam_H_ */
#include "asn_internal.h"
