/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-base.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_McmContainer_H_
#define	_McmContainer_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VehicleManoeuvreContainer.h"
#include "ManoeuvreAdviceContainer.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum McmContainer_PR {
	McmContainer_PR_NOTHING,	/* No components present */
	McmContainer_PR_vehicleManoeuvreContainer,
	McmContainer_PR_manoeuvreAdviceContainer
} McmContainer_PR;

/* McmContainer */
typedef struct McmContainer {
	McmContainer_PR present;
	union McmContainer_u {
		VehicleManoeuvreContainer_t	 vehicleManoeuvreContainer;
		ManoeuvreAdviceContainer_t	 manoeuvreAdviceContainer;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} McmContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_McmContainer;
extern asn_CHOICE_specifics_t asn_SPC_McmContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_McmContainer_1[2];
extern asn_per_constraints_t asn_PER_type_McmContainer_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _McmContainer_H_ */
#include "asn_internal.h"
