/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-base.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_McmStartPoint_H_
#define	_McmStartPoint_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IntermediatePointReference.h"
#include "IntermediatePointOffroad.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum McmStartPoint_PR {
	McmStartPoint_PR_NOTHING,	/* No components present */
	McmStartPoint_PR_intermediatePointReference,
	McmStartPoint_PR_intermediatePointOffroad
} McmStartPoint_PR;

/* McmStartPoint */
typedef struct McmStartPoint {
	McmStartPoint_PR present;
	union McmStartPoint_u {
		IntermediatePointReference_t	 intermediatePointReference;
		IntermediatePointOffroad_t	 intermediatePointOffroad;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} McmStartPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_McmStartPoint;
extern asn_CHOICE_specifics_t asn_SPC_McmStartPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_McmStartPoint_1[2];
extern asn_per_constraints_t asn_PER_type_McmStartPoint_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _McmStartPoint_H_ */
#include "asn_internal.h"
