/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ObjectDimensionV1_H_
#define	_ObjectDimensionV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ObjectDimensionValueV1.h"
#include "ObjectDimensionConfidenceV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ObjectDimensionV1 */
typedef struct ObjectDimensionV1 {
	ObjectDimensionValueV1_t	 value;
	ObjectDimensionConfidenceV1_t	 confidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ObjectDimensionV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ObjectDimensionV1;
extern asn_SEQUENCE_specifics_t asn_SPC_ObjectDimensionV1_specs_1;
extern asn_TYPE_member_t asn_MBR_ObjectDimensionV1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectDimensionV1_H_ */
#include "asn_internal.h"
