/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_OriginatingVehicleContainerV1_H_
#define	_OriginatingVehicleContainerV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Heading.h"
#include "Speed.h"
#include "DriveDirection.h"
#include "VehicleWidth.h"
#include "VehicleHeight.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct WGS84AngleV1;
struct LongitudinalAcceleration;
struct LateralAcceleration;
struct VerticalAcceleration;
struct YawRate;
struct CartesianAngleV1;
struct VehicleLength;
struct TrailerDataContainerV1;

/* OriginatingVehicleContainerV1 */
typedef struct OriginatingVehicleContainerV1 {
	Heading_t	 heading;
	Speed_t	 speed;
	struct WGS84AngleV1	*vehicleOrientationAngle;	/* OPTIONAL */
	DriveDirection_t	 driveDirection;	/* DEFAULT 0 */
	struct LongitudinalAcceleration	*longitudinalAcceleration;	/* OPTIONAL */
	struct LateralAcceleration	*lateralAcceleration;	/* OPTIONAL */
	struct VerticalAcceleration	*verticalAcceleration;	/* OPTIONAL */
	struct YawRate	*yawRate;	/* OPTIONAL */
	struct CartesianAngleV1	*pitchAngle;	/* OPTIONAL */
	struct CartesianAngleV1	*rollAngle;	/* OPTIONAL */
	struct VehicleLength	*vehicleLength;	/* OPTIONAL */
	VehicleWidth_t	*vehicleWidth;	/* OPTIONAL */
	VehicleHeight_t	*vehicleHeight;	/* OPTIONAL */
	struct TrailerDataContainerV1	*trailerDataContainer;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} OriginatingVehicleContainerV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_OriginatingVehicleContainerV1;
extern asn_SEQUENCE_specifics_t asn_SPC_OriginatingVehicleContainerV1_specs_1;
extern asn_TYPE_member_t asn_MBR_OriginatingVehicleContainerV1_1[14];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "WGS84AngleV1.h"
#include "LongitudinalAcceleration.h"
#include "LateralAcceleration.h"
#include "VerticalAcceleration.h"
#include "YawRate.h"
#include "CartesianAngleV1.h"
#include "VehicleLength.h"
#include "TrailerDataContainerV1.h"

#endif	/* _OriginatingVehicleContainerV1_H_ */
#include "asn_internal.h"
