/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PerceivedObjectContainerSegmentInfoV1_H_
#define	_PerceivedObjectContainerSegmentInfoV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SegmentCountV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PerceivedObjectContainerSegmentInfoV1 */
typedef struct PerceivedObjectContainerSegmentInfoV1 {
	SegmentCountV1_t	 totalMsgSegments;
	SegmentCountV1_t	 thisSegmentNum;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerceivedObjectContainerSegmentInfoV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerceivedObjectContainerSegmentInfoV1;
extern asn_SEQUENCE_specifics_t asn_SPC_PerceivedObjectContainerSegmentInfoV1_specs_1;
extern asn_TYPE_member_t asn_MBR_PerceivedObjectContainerSegmentInfoV1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PerceivedObjectContainerSegmentInfoV1_H_ */
#include "asn_internal.h"
