/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PersonSubclassTypeV1_H_
#define	_PersonSubclassTypeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PersonSubclassTypeV1 {
	PersonSubclassTypeV1_unknown	= 0,
	PersonSubclassTypeV1_pedestrian	= 1,
	PersonSubclassTypeV1_personInWheelchair	= 2,
	PersonSubclassTypeV1_cyclist	= 3,
	PersonSubclassTypeV1_personWithStroller	= 4,
	PersonSubclassTypeV1_personOnSkates	= 5,
	PersonSubclassTypeV1_personGroup	= 6
} e_PersonSubclassTypeV1;

/* PersonSubclassTypeV1 */
typedef long	 PersonSubclassTypeV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PersonSubclassTypeV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PersonSubclassTypeV1;
asn_struct_free_f PersonSubclassTypeV1_free;
asn_struct_print_f PersonSubclassTypeV1_print;
asn_constr_check_f PersonSubclassTypeV1_constraint;
ber_type_decoder_f PersonSubclassTypeV1_decode_ber;
der_type_encoder_f PersonSubclassTypeV1_encode_der;
xer_type_decoder_f PersonSubclassTypeV1_decode_xer;
xer_type_encoder_f PersonSubclassTypeV1_encode_xer;
oer_type_decoder_f PersonSubclassTypeV1_decode_oer;
oer_type_encoder_f PersonSubclassTypeV1_encode_oer;
per_type_decoder_f PersonSubclassTypeV1_decode_uper;
per_type_encoder_f PersonSubclassTypeV1_encode_uper;
per_type_decoder_f PersonSubclassTypeV1_decode_aper;
per_type_encoder_f PersonSubclassTypeV1_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PersonSubclassTypeV1_H_ */
#include "asn_internal.h"
