/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PolyPointListV1_H_
#define	_PolyPointListV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OffsetPointV1;

/* PolyPointListV1 */
typedef struct PolyPointListV1 {
	A_SEQUENCE_OF(struct OffsetPointV1) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PolyPointListV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PolyPointListV1;
extern asn_SET_OF_specifics_t asn_SPC_PolyPointListV1_specs_1;
extern asn_TYPE_member_t asn_MBR_PolyPointListV1_1[1];
extern asn_per_constraints_t asn_PER_type_PolyPointListV1_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OffsetPointV1.h"

#endif	/* _PolyPointListV1_H_ */
#include "asn_internal.h"
