/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-base.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PolynomEndX_H_
#define	_PolynomEndX_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PolynomEndX */
typedef long	 PolynomEndX_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PolynomEndX_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PolynomEndX;
asn_struct_free_f PolynomEndX_free;
asn_struct_print_f PolynomEndX_print;
asn_constr_check_f PolynomEndX_constraint;
ber_type_decoder_f PolynomEndX_decode_ber;
der_type_encoder_f PolynomEndX_encode_der;
xer_type_decoder_f PolynomEndX_decode_xer;
xer_type_encoder_f PolynomEndX_encode_xer;
jer_type_encoder_f PolynomEndX_encode_jer;
oer_type_decoder_f PolynomEndX_decode_oer;
oer_type_encoder_f PolynomEndX_encode_oer;
per_type_decoder_f PolynomEndX_decode_uper;
per_type_encoder_f PolynomEndX_encode_uper;
per_type_decoder_f PolynomEndX_decode_aper;
per_type_encoder_f PolynomEndX_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PolynomEndX_H_ */
#include "asn_internal.h"
