/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "MCM-PDU-Descriptions"
 * 	found in "MCM-base.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PolynomStartX_H_
#define	_PolynomStartX_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PolynomStartX */
typedef long	 PolynomStartX_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PolynomStartX_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PolynomStartX;
asn_struct_free_f PolynomStartX_free;
asn_struct_print_f PolynomStartX_print;
asn_constr_check_f PolynomStartX_constraint;
ber_type_decoder_f PolynomStartX_decode_ber;
der_type_encoder_f PolynomStartX_encode_der;
xer_type_decoder_f PolynomStartX_decode_xer;
xer_type_encoder_f PolynomStartX_encode_xer;
jer_type_encoder_f PolynomStartX_encode_jer;
oer_type_decoder_f PolynomStartX_decode_oer;
oer_type_encoder_f PolynomStartX_encode_oer;
per_type_decoder_f PolynomStartX_decode_uper;
per_type_encoder_f PolynomStartX_encode_uper;
per_type_decoder_f PolynomStartX_decode_aper;
per_type_encoder_f PolynomStartX_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PolynomStartX_H_ */
#include "asn_internal.h"
