/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RoadTypeV1_H_
#define	_RoadTypeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RoadTypeV1 {
	RoadTypeV1_urban_NoStructuralSeparationToOppositeLanes	= 0,
	RoadTypeV1_urban_WithStructuralSeparationToOppositeLanes	= 1,
	RoadTypeV1_nonUrban_NoStructuralSeparationToOppositeLanes	= 2,
	RoadTypeV1_nonUrban_WithStructuralSeparationToOppositeLanes	= 3
} e_RoadTypeV1;

/* RoadTypeV1 */
typedef long	 RoadTypeV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RoadTypeV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RoadTypeV1;
extern const asn_INTEGER_specifics_t asn_SPC_RoadTypeV1_specs_1;
asn_struct_free_f RoadTypeV1_free;
asn_struct_print_f RoadTypeV1_print;
asn_constr_check_f RoadTypeV1_constraint;
ber_type_decoder_f RoadTypeV1_decode_ber;
der_type_encoder_f RoadTypeV1_encode_der;
xer_type_decoder_f RoadTypeV1_decode_xer;
xer_type_encoder_f RoadTypeV1_encode_xer;
oer_type_decoder_f RoadTypeV1_decode_oer;
oer_type_encoder_f RoadTypeV1_encode_oer;
per_type_decoder_f RoadTypeV1_decode_uper;
per_type_encoder_f RoadTypeV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _RoadTypeV1_H_ */
#include "asn_internal.h"
