/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SensorInformationV1_H_
#define	_SensorInformationV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "IdentifierV1.h"
#include "SensorTypeV1.h"
#include "DetectionAreaV1.h"
#include "FreeSpaceConfidenceV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SensorInformationV1 */
typedef struct SensorInformationV1 {
	IdentifierV1_t	 sensorID;
	SensorTypeV1_t	 type;
	DetectionAreaV1_t	 detectionArea;
	FreeSpaceConfidenceV1_t	*freeSpaceConfidence;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SensorInformationV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SensorInformationV1;
extern asn_SEQUENCE_specifics_t asn_SPC_SensorInformationV1_specs_1;
extern asn_TYPE_member_t asn_MBR_SensorInformationV1_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SensorInformationV1_H_ */
#include "asn_internal.h"
