/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SequenceNumberV1_H_
#define	_SequenceNumberV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SequenceNumberV1 */
typedef long	 SequenceNumberV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SequenceNumberV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SequenceNumberV1;
asn_struct_free_f SequenceNumberV1_free;
asn_struct_print_f SequenceNumberV1_print;
asn_constr_check_f SequenceNumberV1_constraint;
ber_type_decoder_f SequenceNumberV1_decode_ber;
der_type_encoder_f SequenceNumberV1_encode_der;
xer_type_decoder_f SequenceNumberV1_decode_xer;
xer_type_encoder_f SequenceNumberV1_encode_xer;
oer_type_decoder_f SequenceNumberV1_decode_oer;
oer_type_encoder_f SequenceNumberV1_encode_oer;
per_type_decoder_f SequenceNumberV1_decode_uper;
per_type_encoder_f SequenceNumberV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SequenceNumberV1_H_ */
#include "asn_internal.h"
