/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ShadowingAppliesV1_H_
#define	_ShadowingAppliesV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BOOLEAN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ShadowingAppliesV1 */
typedef BOOLEAN_t	 ShadowingAppliesV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ShadowingAppliesV1;
asn_struct_free_f ShadowingAppliesV1_free;
asn_struct_print_f ShadowingAppliesV1_print;
asn_constr_check_f ShadowingAppliesV1_constraint;
ber_type_decoder_f ShadowingAppliesV1_decode_ber;
der_type_encoder_f ShadowingAppliesV1_encode_der;
xer_type_decoder_f ShadowingAppliesV1_decode_xer;
xer_type_encoder_f ShadowingAppliesV1_encode_xer;
oer_type_decoder_f ShadowingAppliesV1_decode_oer;
oer_type_encoder_f ShadowingAppliesV1_encode_oer;
per_type_decoder_f ShadowingAppliesV1_decode_uper;
per_type_encoder_f ShadowingAppliesV1_encode_uper;
per_type_decoder_f ShadowingAppliesV1_decode_aper;
per_type_encoder_f ShadowingAppliesV1_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ShadowingAppliesV1_H_ */
#include "asn_internal.h"
