/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "/mnt/EVO/ASN1-C-ITS/IVI-payload.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_TrailerCharacteristicsIVI_H_
#define	_TrailerCharacteristicsIVI_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TrailerCharacteristicsFixValuesList;
struct TrailerCharacteristicsRangesList;

/* TrailerCharacteristicsIVI */
typedef struct TrailerCharacteristicsIVI {
	struct TrailerCharacteristicsFixValuesList	*equalTo	/* OPTIONAL */;
	struct TrailerCharacteristicsFixValuesList	*notEqualTo	/* OPTIONAL */;
	struct TrailerCharacteristicsRangesList	*ranges	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TrailerCharacteristicsIVI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrailerCharacteristicsIVI;
extern asn_SEQUENCE_specifics_t asn_SPC_TrailerCharacteristicsIVI_specs_1;
extern asn_TYPE_member_t asn_MBR_TrailerCharacteristicsIVI_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "TrailerCharacteristicsFixValuesList.h"
#include "TrailerCharacteristicsRangesList.h"

#endif	/* _TrailerCharacteristicsIVI_H_ */
#include "asn_internal.h"
