/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_TrailerLicencePlateNumber_H_
#define	_TrailerLicencePlateNumber_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LPN.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TrailerLicencePlateNumber */
typedef LPN_t	 TrailerLicencePlateNumber_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TrailerLicencePlateNumber;
asn_struct_free_f TrailerLicencePlateNumber_free;
asn_struct_print_f TrailerLicencePlateNumber_print;
asn_constr_check_f TrailerLicencePlateNumber_constraint;
ber_type_decoder_f TrailerLicencePlateNumber_decode_ber;
der_type_encoder_f TrailerLicencePlateNumber_encode_der;
xer_type_decoder_f TrailerLicencePlateNumber_decode_xer;
xer_type_encoder_f TrailerLicencePlateNumber_encode_xer;
oer_type_decoder_f TrailerLicencePlateNumber_decode_oer;
oer_type_encoder_f TrailerLicencePlateNumber_encode_oer;
per_type_decoder_f TrailerLicencePlateNumber_decode_uper;
per_type_encoder_f TrailerLicencePlateNumber_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TrailerLicencePlateNumber_H_ */
#include "asn_internal.h"
