/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_VehicleSensorPropertiesV1_H_
#define	_VehicleSensorPropertiesV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RangeV1.h"
#include "CartesianAngleValueV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleSensorPropertiesV1 */
typedef struct VehicleSensorPropertiesV1 {
	RangeV1_t	 range;
	CartesianAngleValueV1_t	 horizontalOpeningAngleStart;
	CartesianAngleValueV1_t	 horizontalOpeningAngleEnd;
	CartesianAngleValueV1_t	*verticalOpeningAngleStart;	/* OPTIONAL */
	CartesianAngleValueV1_t	*verticalOpeningAngleEnd;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSensorPropertiesV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSensorPropertiesV1;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleSensorPropertiesV1_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleSensorPropertiesV1_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSensorPropertiesV1_H_ */
#include "asn_internal.h"
