/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "/mnt/EVO/asn1c-forks/output/CPM-all.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_VehicleLengthV2_H_
#define	_VehicleLengthV2_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VehicleLengthValue.h"
#include "TrailerPresenceInformation.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleLengthV2 */
typedef struct VehicleLengthV2 {
	VehicleLengthValue_t	 vehicleLengthValue;
	TrailerPresenceInformation_t	 trailerPresenceInformation;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleLengthV2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleLengthV2;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleLengthV2_H_ */
#include "asn_internal.h"
