/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_YawRateConfidenceV1_H_
#define	_YawRateConfidenceV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum YawRateConfidenceV1 {
	YawRateConfidenceV1_degSec_000_01	= 0,
	YawRateConfidenceV1_degSec_000_05	= 1,
	YawRateConfidenceV1_degSec_000_10	= 2,
	YawRateConfidenceV1_degSec_001_00	= 3,
	YawRateConfidenceV1_degSec_005_00	= 4,
	YawRateConfidenceV1_degSec_010_00	= 5,
	YawRateConfidenceV1_degSec_100_00	= 6,
	YawRateConfidenceV1_outOfRange	= 7,
	YawRateConfidenceV1_unavailable	= 8
} e_YawRateConfidenceV1;

/* YawRateConfidenceV1 */
typedef long	 YawRateConfidenceV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_YawRateConfidenceV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_YawRateConfidenceV1;
extern const asn_INTEGER_specifics_t asn_SPC_YawRateConfidenceV1_specs_1;
asn_struct_free_f YawRateConfidenceV1_free;
asn_struct_print_f YawRateConfidenceV1_print;
asn_constr_check_f YawRateConfidenceV1_constraint;
ber_type_decoder_f YawRateConfidenceV1_decode_ber;
der_type_encoder_f YawRateConfidenceV1_encode_der;
xer_type_decoder_f YawRateConfidenceV1_decode_xer;
xer_type_encoder_f YawRateConfidenceV1_encode_xer;
oer_type_decoder_f YawRateConfidenceV1_decode_oer;
oer_type_encoder_f YawRateConfidenceV1_encode_oer;
per_type_decoder_f YawRateConfidenceV1_decode_uper;
per_type_encoder_f YawRateConfidenceV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _YawRateConfidenceV1_H_ */
#include "asn_internal.h"
