# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('gps-tc', ['core','mobility'])
    module.source = [
        'model/gps-tc.cc',
        'model/GeographicLib/utmups.c',        
        'model/GeographicLib/utmups_math.c',
        'helper/gps-tc-helper.cc',
        ]

    module_test = bld.create_ns3_module_test_library('gps-tc')
    module_test.source = [
        'test/gps-tc-test-suite.cc',
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    'test/gps-tc-examples-test-suite.cc',
             ])

    headers = bld(features='ns3header')
    headers.module = 'gps-tc'
    headers.source = [
        'model/gps-tc.h',
        'model/GeographicLib/utmups.h',        
        'model/GeographicLib/utmups_math.h',
        'helper/gps-tc-helper.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        bld.recurse('examples')

    # bld.ns3_python_bindings()

