/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ActionIDV1_H_
#define	_ActionIDV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "StationIDV1.h"
#include "SequenceNumberV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ActionIDV1 */
typedef struct ActionIDV1 {
	StationIDV1_t	 originatingStationID;
	SequenceNumberV1_t	 sequenceNumber;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ActionIDV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ActionIDV1;
extern asn_SEQUENCE_specifics_t asn_SPC_ActionIDV1_specs_1;
extern asn_TYPE_member_t asn_MBR_ActionIDV1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _ActionIDV1_H_ */
#include "asn_internal.h"
