/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/home/carlosrisma/IVIM ASN1 files/asn1_IS_ISO_TS_14906_EfcDsrcApplication.asn"
 * 	`asn1c -fincludes-quoted`
 */

#ifndef	_ActualNumberOfPassengers_H_
#define	_ActualNumberOfPassengers_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Int1.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ActualNumberOfPassengers */
typedef Int1_t	 ActualNumberOfPassengers_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ActualNumberOfPassengers;
asn_struct_free_f ActualNumberOfPassengers_free;
asn_struct_print_f ActualNumberOfPassengers_print;
asn_constr_check_f ActualNumberOfPassengers_constraint;
ber_type_decoder_f ActualNumberOfPassengers_decode_ber;
der_type_encoder_f ActualNumberOfPassengers_encode_der;
xer_type_decoder_f ActualNumberOfPassengers_decode_xer;
xer_type_encoder_f ActualNumberOfPassengers_encode_xer;
oer_type_decoder_f ActualNumberOfPassengers_decode_oer;
oer_type_encoder_f ActualNumberOfPassengers_encode_oer;
per_type_decoder_f ActualNumberOfPassengers_decode_uper;
per_type_encoder_f ActualNumberOfPassengers_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ActualNumberOfPassengers_H_ */
#include "asn_internal.h"
