/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_CauseCodeV1_H_
#define	_CauseCodeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CauseCodeTypeV1.h"
#include "SubCauseCodeTypeV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CauseCodeV1 */
typedef struct CauseCodeV1 {
	CauseCodeTypeV1_t	 causeCode;
	SubCauseCodeTypeV1_t	 subCauseCode;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CauseCodeV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CauseCodeV1;
extern asn_SEQUENCE_specifics_t asn_SPC_CauseCodeV1_specs_1;
extern asn_TYPE_member_t asn_MBR_CauseCodeV1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CauseCodeV1_H_ */
#include "asn_internal.h"
