/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PMU-PDU-Descriptions"
 * 	found in "PMU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ConnectedVehiclesIDs_H_
#define	_ConnectedVehiclesIDs_H_


#include "asn_application.h"

/* Including external dependencies */
#include "StationID.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ConnectedVehiclesIDs */
typedef struct ConnectedVehiclesIDs {
	A_SEQUENCE_OF(StationID_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConnectedVehiclesIDs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConnectedVehiclesIDs;
extern asn_SET_OF_specifics_t asn_SPC_ConnectedVehiclesIDs_specs_1;
extern asn_TYPE_member_t asn_MBR_ConnectedVehiclesIDs_1[1];
extern asn_per_constraints_t asn_PER_type_ConnectedVehiclesIDs_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ConnectedVehiclesIDs_H_ */
#include "asn_internal.h"
