/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpC"
 * 	found in "/home/carlosrisma/IVIM ASN1 files/ISO-TS-19091.asn"
 * 	`asn1c -fincludes-quoted`
 */

#include "ConnectionTrajectory-addGrpC.h"

static asn_TYPE_member_t asn_MBR_ConnectionTrajectory_addGrpC_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConnectionTrajectory_addGrpC, nodes),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NodeSetXY,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nodes"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConnectionTrajectory_addGrpC, connectionID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LaneConnectionID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"connectionID"
		},
};
static const ber_tlv_tag_t asn_DEF_ConnectionTrajectory_addGrpC_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ConnectionTrajectory_addGrpC_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* nodes */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* connectionID */
};
static asn_SEQUENCE_specifics_t asn_SPC_ConnectionTrajectory_addGrpC_specs_1 = {
	sizeof(struct ConnectionTrajectory_addGrpC),
	offsetof(struct ConnectionTrajectory_addGrpC, _asn_ctx),
	asn_MAP_ConnectionTrajectory_addGrpC_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ConnectionTrajectory_addGrpC = {
	"ConnectionTrajectory-addGrpC",
	"ConnectionTrajectory-addGrpC",
	&asn_OP_SEQUENCE,
	asn_DEF_ConnectionTrajectory_addGrpC_tags_1,
	sizeof(asn_DEF_ConnectionTrajectory_addGrpC_tags_1)
		/sizeof(asn_DEF_ConnectionTrajectory_addGrpC_tags_1[0]), /* 1 */
	asn_DEF_ConnectionTrajectory_addGrpC_tags_1,	/* Same as above */
	sizeof(asn_DEF_ConnectionTrajectory_addGrpC_tags_1)
		/sizeof(asn_DEF_ConnectionTrajectory_addGrpC_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ConnectionTrajectory_addGrpC_1,
	2,	/* Elements count */
	&asn_SPC_ConnectionTrajectory_addGrpC_specs_1	/* Additional specs */
};

