/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "CAM-PDU-Descriptions-1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_CoopAwarenessV1_H_
#define	_CoopAwarenessV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "GenerationDeltaTimeV1.h"
#include "CamParametersV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* CoopAwarenessV1 */
typedef struct CoopAwarenessV1 {
	GenerationDeltaTimeV1_t	 generationDeltaTime;
	CamParametersV1_t	 camParameters;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CoopAwarenessV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CoopAwarenessV1;
extern asn_SEQUENCE_specifics_t asn_SPC_CoopAwarenessV1_specs_1;
extern asn_TYPE_member_t asn_MBR_CoopAwarenessV1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CoopAwarenessV1_H_ */
#include "asn_internal.h"
