/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_DangerousGoodsBasicV1_H_
#define	_DangerousGoodsBasicV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DangerousGoodsBasicV1 {
	DangerousGoodsBasicV1_explosives1	= 0,
	DangerousGoodsBasicV1_explosives2	= 1,
	DangerousGoodsBasicV1_explosives3	= 2,
	DangerousGoodsBasicV1_explosives4	= 3,
	DangerousGoodsBasicV1_explosives5	= 4,
	DangerousGoodsBasicV1_explosives6	= 5,
	DangerousGoodsBasicV1_flammableGases	= 6,
	DangerousGoodsBasicV1_nonFlammableGases	= 7,
	DangerousGoodsBasicV1_toxicGases	= 8,
	DangerousGoodsBasicV1_flammableLiquids	= 9,
	DangerousGoodsBasicV1_flammableSolids	= 10,
	DangerousGoodsBasicV1_substancesLiableToSpontaneousCombustion	= 11,
	DangerousGoodsBasicV1_substancesEmittingFlammableGasesUponContactWithWater	= 12,
	DangerousGoodsBasicV1_oxidizingSubstances	= 13,
	DangerousGoodsBasicV1_organicPeroxides	= 14,
	DangerousGoodsBasicV1_toxicSubstances	= 15,
	DangerousGoodsBasicV1_infectiousSubstances	= 16,
	DangerousGoodsBasicV1_radioactiveMaterial	= 17,
	DangerousGoodsBasicV1_corrosiveSubstances	= 18,
	DangerousGoodsBasicV1_miscellaneousDangerousSubstances	= 19
} e_DangerousGoodsBasicV1;

/* DangerousGoodsBasicV1 */
typedef long	 DangerousGoodsBasicV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DangerousGoodsBasicV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DangerousGoodsBasicV1;
extern const asn_INTEGER_specifics_t asn_SPC_DangerousGoodsBasicV1_specs_1;
asn_struct_free_f DangerousGoodsBasicV1_free;
asn_struct_print_f DangerousGoodsBasicV1_print;
asn_constr_check_f DangerousGoodsBasicV1_constraint;
ber_type_decoder_f DangerousGoodsBasicV1_decode_ber;
der_type_encoder_f DangerousGoodsBasicV1_encode_der;
xer_type_decoder_f DangerousGoodsBasicV1_decode_xer;
xer_type_encoder_f DangerousGoodsBasicV1_encode_xer;
oer_type_decoder_f DangerousGoodsBasicV1_decode_oer;
oer_type_encoder_f DangerousGoodsBasicV1_encode_oer;
per_type_decoder_f DangerousGoodsBasicV1_decode_uper;
per_type_encoder_f DangerousGoodsBasicV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DangerousGoodsBasicV1_H_ */
#include "asn_internal.h"
