/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "DENM-PDU-Descriptions-1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_DENMV1_H_
#define	_DENMV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ItsPduHeaderV1.h"
#include "DecentralizedEnvironmentalNotificationMessageV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* DENMV1 */
typedef struct DENMV1 {
	ItsPduHeaderV1_t	 header;
	DecentralizedEnvironmentalNotificationMessageV1_t	 denm;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DENMV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DENMV1;

#ifdef __cplusplus
}
#endif

#endif	/* _DENMV1_H_ */
#include "asn_internal.h"
