/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_EnergyStorageTypeV1_H_
#define	_EnergyStorageTypeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BIT_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum EnergyStorageTypeV1 {
	EnergyStorageTypeV1_hydrogenStorage	= 0,
	EnergyStorageTypeV1_electricEnergyStorage	= 1,
	EnergyStorageTypeV1_liquidPropaneGas	= 2,
	EnergyStorageTypeV1_compressedNaturalGas	= 3,
	EnergyStorageTypeV1_diesel	= 4,
	EnergyStorageTypeV1_gasoline	= 5,
	EnergyStorageTypeV1_ammonia	= 6
} e_EnergyStorageTypeV1;

/* EnergyStorageTypeV1 */
typedef BIT_STRING_t	 EnergyStorageTypeV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_EnergyStorageTypeV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_EnergyStorageTypeV1;
asn_struct_free_f EnergyStorageTypeV1_free;
asn_struct_print_f EnergyStorageTypeV1_print;
asn_constr_check_f EnergyStorageTypeV1_constraint;
ber_type_decoder_f EnergyStorageTypeV1_decode_ber;
der_type_encoder_f EnergyStorageTypeV1_encode_der;
xer_type_decoder_f EnergyStorageTypeV1_decode_xer;
xer_type_encoder_f EnergyStorageTypeV1_encode_xer;
oer_type_decoder_f EnergyStorageTypeV1_decode_oer;
oer_type_encoder_f EnergyStorageTypeV1_encode_oer;
per_type_decoder_f EnergyStorageTypeV1_decode_uper;
per_type_encoder_f EnergyStorageTypeV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _EnergyStorageTypeV1_H_ */
#include "asn_internal.h"
