/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_HardShoulderStatusV1_H_
#define	_HardShoulderStatusV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HardShoulderStatusV1 {
	HardShoulderStatusV1_availableForStopping	= 0,
	HardShoulderStatusV1_closed	= 1,
	HardShoulderStatusV1_availableForDriving	= 2
} e_HardShoulderStatusV1;

/* HardShoulderStatusV1 */
typedef long	 HardShoulderStatusV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_HardShoulderStatusV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_HardShoulderStatusV1;
extern const asn_INTEGER_specifics_t asn_SPC_HardShoulderStatusV1_specs_1;
asn_struct_free_f HardShoulderStatusV1_free;
asn_struct_print_f HardShoulderStatusV1_print;
asn_constr_check_f HardShoulderStatusV1_constraint;
ber_type_decoder_f HardShoulderStatusV1_decode_ber;
der_type_encoder_f HardShoulderStatusV1_encode_der;
xer_type_decoder_f HardShoulderStatusV1_decode_xer;
xer_type_encoder_f HardShoulderStatusV1_encode_xer;
oer_type_decoder_f HardShoulderStatusV1_decode_oer;
oer_type_encoder_f HardShoulderStatusV1_encode_oer;
per_type_decoder_f HardShoulderStatusV1_decode_uper;
per_type_encoder_f HardShoulderStatusV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HardShoulderStatusV1_H_ */
#include "asn_internal.h"
