/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_HazardousLocation_DangerousCurveSubCauseCodeV1_H_
#define	_HazardousLocation_DangerousCurveSubCauseCodeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum HazardousLocation_DangerousCurveSubCauseCodeV1 {
	HazardousLocation_DangerousCurveSubCauseCodeV1_unavailable	= 0,
	HazardousLocation_DangerousCurveSubCauseCodeV1_dangerousLeftTurnCurve	= 1,
	HazardousLocation_DangerousCurveSubCauseCodeV1_dangerousRightTurnCurve	= 2,
	HazardousLocation_DangerousCurveSubCauseCodeV1_multipleCurvesStartingWithUnknownTurningDirection	= 3,
	HazardousLocation_DangerousCurveSubCauseCodeV1_multipleCurvesStartingWithLeftTurn	= 4,
	HazardousLocation_DangerousCurveSubCauseCodeV1_multipleCurvesStartingWithRightTurn	= 5
} e_HazardousLocation_DangerousCurveSubCauseCodeV1;

/* HazardousLocation-DangerousCurveSubCauseCodeV1 */
typedef long	 HazardousLocation_DangerousCurveSubCauseCodeV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_HazardousLocation_DangerousCurveSubCauseCodeV1;
asn_struct_free_f HazardousLocation_DangerousCurveSubCauseCodeV1_free;
asn_struct_print_f HazardousLocation_DangerousCurveSubCauseCodeV1_print;
asn_constr_check_f HazardousLocation_DangerousCurveSubCauseCodeV1_constraint;
ber_type_decoder_f HazardousLocation_DangerousCurveSubCauseCodeV1_decode_ber;
der_type_encoder_f HazardousLocation_DangerousCurveSubCauseCodeV1_encode_der;
xer_type_decoder_f HazardousLocation_DangerousCurveSubCauseCodeV1_decode_xer;
xer_type_encoder_f HazardousLocation_DangerousCurveSubCauseCodeV1_encode_xer;
oer_type_decoder_f HazardousLocation_DangerousCurveSubCauseCodeV1_decode_oer;
oer_type_encoder_f HazardousLocation_DangerousCurveSubCauseCodeV1_encode_oer;
per_type_decoder_f HazardousLocation_DangerousCurveSubCauseCodeV1_decode_uper;
per_type_encoder_f HazardousLocation_DangerousCurveSubCauseCodeV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _HazardousLocation_DangerousCurveSubCauseCodeV1_H_ */
#include "asn_internal.h"
