/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 */

#ifndef	_Identifier2B_H_
#define	_Identifier2B_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Identifier2B */
typedef long	 Identifier2B_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Identifier2B_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Identifier2B;
asn_struct_free_f Identifier2B_free;
asn_struct_print_f Identifier2B_print;
asn_constr_check_f Identifier2B_constraint;
ber_type_decoder_f Identifier2B_decode_ber;
der_type_encoder_f Identifier2B_encode_der;
xer_type_decoder_f Identifier2B_decode_xer;
xer_type_encoder_f Identifier2B_encode_xer;
oer_type_decoder_f Identifier2B_decode_oer;
oer_type_encoder_f Identifier2B_encode_oer;
per_type_decoder_f Identifier2B_decode_uper;
per_type_encoder_f Identifier2B_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _Identifier2B_H_ */
#include "asn_internal.h"
