/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "DENM-PDU-Descriptions-1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ImpactReductionContainerV1_H_
#define	_ImpactReductionContainerV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "HeightLonCarrV1.h"
#include "PosLonCarrV1.h"
#include "PositionOfPillarsV1.h"
#include "PosCentMassV1.h"
#include "WheelBaseVehicleV1.h"
#include "TurningRadiusV1.h"
#include "PosFrontAxV1.h"
#include "PositionOfOccupantsV1.h"
#include "VehicleMassV1.h"
#include "RequestResponseIndicationV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ImpactReductionContainerV1 */
typedef struct ImpactReductionContainerV1 {
	HeightLonCarrV1_t	 heightLonCarrLeft;
	HeightLonCarrV1_t	 heightLonCarrRight;
	PosLonCarrV1_t	 posLonCarrLeft;
	PosLonCarrV1_t	 posLonCarrRight;
	PositionOfPillarsV1_t	 positionOfPillars;
	PosCentMassV1_t	 posCentMass;
	WheelBaseVehicleV1_t	 wheelBaseVehicle;
	TurningRadiusV1_t	 turningRadius;
	PosFrontAxV1_t	 posFrontAx;
	PositionOfOccupantsV1_t	 positionOfOccupants;
	VehicleMassV1_t	 vehicleMass;
	RequestResponseIndicationV1_t	 requestResponseIndication;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ImpactReductionContainerV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ImpactReductionContainerV1;
extern asn_SEQUENCE_specifics_t asn_SPC_ImpactReductionContainerV1_specs_1;
extern asn_TYPE_member_t asn_MBR_ImpactReductionContainerV1_1[12];

#ifdef __cplusplus
}
#endif

#endif	/* _ImpactReductionContainerV1_H_ */
#include "asn_internal.h"
