/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "GDD"
 * 	found in "/home/carlosrisma/IVIM ASN1 files/asn1_IS_ISO_TS_14823_GDD.asn"
 * 	`asn1c -fincludes-quoted`
 */

#ifndef	_InternationalSign_distanceBetweenVehicles_H_
#define	_InternationalSign_distanceBetweenVehicles_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Distance.h"

#ifdef __cplusplus
extern "C" {
#endif

/* InternationalSign-distanceBetweenVehicles */
typedef Distance_t	 InternationalSign_distanceBetweenVehicles_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_InternationalSign_distanceBetweenVehicles;
asn_struct_free_f InternationalSign_distanceBetweenVehicles_free;
asn_struct_print_f InternationalSign_distanceBetweenVehicles_print;
asn_constr_check_f InternationalSign_distanceBetweenVehicles_constraint;
ber_type_decoder_f InternationalSign_distanceBetweenVehicles_decode_ber;
der_type_encoder_f InternationalSign_distanceBetweenVehicles_encode_der;
xer_type_decoder_f InternationalSign_distanceBetweenVehicles_decode_xer;
xer_type_encoder_f InternationalSign_distanceBetweenVehicles_encode_xer;
oer_type_decoder_f InternationalSign_distanceBetweenVehicles_decode_oer;
oer_type_encoder_f InternationalSign_distanceBetweenVehicles_encode_oer;
per_type_decoder_f InternationalSign_distanceBetweenVehicles_decode_uper;
per_type_encoder_f InternationalSign_distanceBetweenVehicles_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _InternationalSign_distanceBetweenVehicles_H_ */
#include "asn_internal.h"
