/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "DENM-PDU-Descriptions-1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ManagementContainerV1_H_
#define	_ManagementContainerV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ActionIDV1.h"
#include "TimestampItsV1.h"
#include "TerminationV1.h"
#include "ReferencePositionV1.h"
#include "RelevanceDistanceV1.h"
#include "RelevanceTrafficDirectionV1.h"
#include "ValidityDurationV1.h"
#include "TransmissionIntervalV1.h"
#include "StationTypeV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ManagementContainerV1 */
typedef struct ManagementContainerV1 {
	ActionIDV1_t	 actionID;
	TimestampItsV1_t	 detectionTime;
	TimestampItsV1_t	 referenceTime;
	TerminationV1_t	*termination	/* OPTIONAL */;
	ReferencePositionV1_t	 eventPosition;
	RelevanceDistanceV1_t	*relevanceDistance	/* OPTIONAL */;
	RelevanceTrafficDirectionV1_t	*relevanceTrafficDirection	/* OPTIONAL */;
	ValidityDurationV1_t	*validityDuration	/* DEFAULT 600 */;
	TransmissionIntervalV1_t	*transmissionInterval	/* OPTIONAL */;
	StationTypeV1_t	 stationType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ManagementContainerV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ManagementContainerV1;
extern asn_SEQUENCE_specifics_t asn_SPC_ManagementContainerV1_specs_1;
extern asn_TYPE_member_t asn_MBR_ManagementContainerV1_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _ManagementContainerV1_H_ */
#include "asn_internal.h"
