/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 */

#include "MessageRateHz.h"

static int
memb_mantissa_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 1 && value <= 100)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_exponent_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= -5 && value <= 2)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_mantissa_constr_2 CC_NOTUSED = {
	{ 1, 1 }	/* (1..100) */,
	-1};
static asn_per_constraints_t asn_PER_memb_mantissa_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  1,  100 }	/* (1..100) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_exponent_constr_3 CC_NOTUSED = {
	{ 1, 0 }	/* (-5..2) */,
	-1};
static asn_per_constraints_t asn_PER_memb_exponent_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 3,  3, -5,  2 }	/* (-5..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_MessageRateHz_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MessageRateHz, mantissa),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_mantissa_constr_2, &asn_PER_memb_mantissa_constr_2,  memb_mantissa_constraint_1 },
		0, 0, /* No default value */
		"mantissa"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MessageRateHz, exponent),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_exponent_constr_3, &asn_PER_memb_exponent_constr_3,  memb_exponent_constraint_1 },
		0, 0, /* No default value */
		"exponent"
		},
};
static const ber_tlv_tag_t asn_DEF_MessageRateHz_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_MessageRateHz_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* mantissa */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* exponent */
};
static asn_SEQUENCE_specifics_t asn_SPC_MessageRateHz_specs_1 = {
	sizeof(struct MessageRateHz),
	offsetof(struct MessageRateHz, _asn_ctx),
	asn_MAP_MessageRateHz_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_MessageRateHz = {
	"MessageRateHz",
	"MessageRateHz",
	&asn_OP_SEQUENCE,
	asn_DEF_MessageRateHz_tags_1,
	sizeof(asn_DEF_MessageRateHz_tags_1)
		/sizeof(asn_DEF_MessageRateHz_tags_1[0]), /* 1 */
	asn_DEF_MessageRateHz_tags_1,	/* Same as above */
	sizeof(asn_DEF_MessageRateHz_tags_1)
		/sizeof(asn_DEF_MessageRateHz_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_MessageRateHz_1,
	2,	/* Elements count */
	&asn_SPC_MessageRateHz_specs_1	/* Additional specs */
};

