/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 */

#ifndef	_MessageSegmentationInfo_H_
#define	_MessageSegmentationInfo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CardinalNumber3b.h"
#include "OrdinalNumber3b.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* MessageSegmentationInfo */
typedef struct MessageSegmentationInfo {
	CardinalNumber3b_t	 totalMsgNo;
	OrdinalNumber3b_t	 thisMsgNo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MessageSegmentationInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_MessageSegmentationInfo;

#ifdef __cplusplus
}
#endif

#endif	/* _MessageSegmentationInfo_H_ */
#include "asn_internal.h"
