/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PMU-PDU-Descriptions"
 * 	found in "PMU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PerceivedPPOIDs_H_
#define	_PerceivedPPOIDs_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Identifier.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PerceivedPPOIDs */
typedef struct PerceivedPPOIDs {
	A_SEQUENCE_OF(Identifier_t) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerceivedPPOIDs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerceivedPPOIDs;
extern asn_SET_OF_specifics_t asn_SPC_PerceivedPPOIDs_specs_1;
extern asn_TYPE_member_t asn_MBR_PerceivedPPOIDs_1[1];
extern asn_per_constraints_t asn_PER_type_PerceivedPPOIDs_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _PerceivedPPOIDs_H_ */
#include "asn_internal.h"
