/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PMU-PDU-Descriptions"
 * 	found in "PMU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PlatoonMemberState_H_
#define	_PlatoonMemberState_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AvailableCPU.h"
#include "NumberOfPerceivedObjects.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PerceivedPPOIDs;

/* PlatoonMemberState */
typedef struct PlatoonMemberState {
	AvailableCPU_t	 availableCPUs;
	NumberOfPerceivedObjects_t	 numberOfPerceivedObjectsResponsible;
	struct PerceivedPPOIDs	*perceivedPPOIDs	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PlatoonMemberState_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PlatoonMemberState;
extern asn_SEQUENCE_specifics_t asn_SPC_PlatoonMemberState_specs_1;
extern asn_TYPE_member_t asn_MBR_PlatoonMemberState_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PerceivedPPOIDs.h"

#endif	/* _PlatoonMemberState_H_ */
#include "asn_internal.h"
