/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PMU-PDU-Descriptions"
 * 	found in "PMU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "PlatoonMemberState.h"

asn_TYPE_member_t asn_MBR_PlatoonMemberState_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PlatoonMemberState, availableCPUs),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AvailableCPU,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"availableCPUs"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PlatoonMemberState, numberOfPerceivedObjectsResponsible),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NumberOfPerceivedObjects,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"numberOfPerceivedObjectsResponsible"
		},
	{ ATF_POINTER, 1, offsetof(struct PlatoonMemberState, perceivedPPOIDs),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PerceivedPPOIDs,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"perceivedPPOIDs"
		},
};
static const int asn_MAP_PlatoonMemberState_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_PlatoonMemberState_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PlatoonMemberState_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* availableCPUs */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* numberOfPerceivedObjectsResponsible */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* perceivedPPOIDs */
};
asn_SEQUENCE_specifics_t asn_SPC_PlatoonMemberState_specs_1 = {
	sizeof(struct PlatoonMemberState),
	offsetof(struct PlatoonMemberState, _asn_ctx),
	asn_MAP_PlatoonMemberState_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_PlatoonMemberState_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PlatoonMemberState = {
	"PlatoonMemberState",
	"PlatoonMemberState",
	&asn_OP_SEQUENCE,
	asn_DEF_PlatoonMemberState_tags_1,
	sizeof(asn_DEF_PlatoonMemberState_tags_1)
		/sizeof(asn_DEF_PlatoonMemberState_tags_1[0]), /* 1 */
	asn_DEF_PlatoonMemberState_tags_1,	/* Same as above */
	sizeof(asn_DEF_PlatoonMemberState_tags_1)
		/sizeof(asn_DEF_PlatoonMemberState_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PlatoonMemberState_1,
	3,	/* Elements count */
	&asn_SPC_PlatoonMemberState_specs_1	/* Additional specs */
};

