/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PLU-PDU-Descriptions"
 * 	found in "PLU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "PlatoonLeaderUpdate.h"

asn_TYPE_member_t asn_MBR_PlatoonLeaderUpdate_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PlatoonLeaderUpdate, platoonLeaderContainer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OriginatingVehicleContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"platoonLeaderContainer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PlatoonLeaderUpdate, platoonMembers),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PlatoonMembers,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"platoonMembers"
		},
	{ ATF_POINTER, 2, offsetof(struct PlatoonLeaderUpdate, nonPlatoonMembers),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NonPlatoonMembers,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nonPlatoonMembers"
		},
	{ ATF_POINTER, 1, offsetof(struct PlatoonLeaderUpdate, platoonPerceivedObjectsContainer),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PlatoonPerceivedObjectsContainer,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"platoonPerceivedObjectsContainer"
		},
};
static const int asn_MAP_PlatoonLeaderUpdate_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_PlatoonLeaderUpdate_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PlatoonLeaderUpdate_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* platoonLeaderContainer */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* platoonMembers */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* nonPlatoonMembers */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* platoonPerceivedObjectsContainer */
};
asn_SEQUENCE_specifics_t asn_SPC_PlatoonLeaderUpdate_specs_1 = {
	sizeof(struct PlatoonLeaderUpdate),
	offsetof(struct PlatoonLeaderUpdate, _asn_ctx),
	asn_MAP_PlatoonLeaderUpdate_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_PlatoonLeaderUpdate_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PlatoonLeaderUpdate = {
	"PlatoonLeaderUpdate",
	"PlatoonLeaderUpdate",
	&asn_OP_SEQUENCE,
	asn_DEF_PlatoonLeaderUpdate_tags_1,
	sizeof(asn_DEF_PlatoonLeaderUpdate_tags_1)
		/sizeof(asn_DEF_PlatoonLeaderUpdate_tags_1[0]), /* 1 */
	asn_DEF_PlatoonLeaderUpdate_tags_1,	/* Same as above */
	sizeof(asn_DEF_PlatoonLeaderUpdate_tags_1)
		/sizeof(asn_DEF_PlatoonLeaderUpdate_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PlatoonLeaderUpdate_1,
	4,	/* Elements count */
	&asn_SPC_PlatoonLeaderUpdate_specs_1	/* Additional specs */
};

