/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "PMU-PDU-Descriptions"
 * 	found in "PMU.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PMU_H_
#define	_PMU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "ItsPduHeader.h"
#include "PlatoonMemberUpdate.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PMU */
typedef struct PMU {
	ItsPduHeader_t	 header;
	PlatoonMemberUpdate_t	 pmu;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PMU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PMU;

#ifdef __cplusplus
}
#endif

#endif	/* _PMU_H_ */
#include "asn_internal.h"
