/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ProtectedZoneIDV1_H_
#define	_ProtectedZoneIDV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ProtectedZoneIDV1 */
typedef long	 ProtectedZoneIDV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ProtectedZoneIDV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtectedZoneIDV1;
asn_struct_free_f ProtectedZoneIDV1_free;
asn_struct_print_f ProtectedZoneIDV1_print;
asn_constr_check_f ProtectedZoneIDV1_constraint;
ber_type_decoder_f ProtectedZoneIDV1_decode_ber;
der_type_encoder_f ProtectedZoneIDV1_encode_der;
xer_type_decoder_f ProtectedZoneIDV1_decode_xer;
xer_type_encoder_f ProtectedZoneIDV1_encode_xer;
oer_type_decoder_f ProtectedZoneIDV1_decode_oer;
oer_type_encoder_f ProtectedZoneIDV1_encode_oer;
per_type_decoder_f ProtectedZoneIDV1_decode_uper;
per_type_encoder_f ProtectedZoneIDV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtectedZoneIDV1_H_ */
#include "asn_internal.h"
