/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "CAM-PDU-Descriptions-1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#include "SafetyCarContainerV1.h"

asn_TYPE_member_t asn_MBR_SafetyCarContainerV1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SafetyCarContainerV1, lightBarSirenInUse),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LightBarSirenInUseV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lightBarSirenInUse"
		},
	{ ATF_POINTER, 3, offsetof(struct SafetyCarContainerV1, incidentIndication),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CauseCodeV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"incidentIndication"
		},
	{ ATF_POINTER, 2, offsetof(struct SafetyCarContainerV1, trafficRule),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TrafficRuleV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"trafficRule"
		},
	{ ATF_POINTER, 1, offsetof(struct SafetyCarContainerV1, speedLimit),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SpeedLimitV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"speedLimit"
		},
};
static const int asn_MAP_SafetyCarContainerV1_oms_1[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_SafetyCarContainerV1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SafetyCarContainerV1_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* lightBarSirenInUse */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* incidentIndication */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* trafficRule */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* speedLimit */
};
asn_SEQUENCE_specifics_t asn_SPC_SafetyCarContainerV1_specs_1 = {
	sizeof(struct SafetyCarContainerV1),
	offsetof(struct SafetyCarContainerV1, _asn_ctx),
	asn_MAP_SafetyCarContainerV1_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_SafetyCarContainerV1_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SafetyCarContainerV1 = {
	"SafetyCarContainerV1",
	"SafetyCarContainerV1",
	&asn_OP_SEQUENCE,
	asn_DEF_SafetyCarContainerV1_tags_1,
	sizeof(asn_DEF_SafetyCarContainerV1_tags_1)
		/sizeof(asn_DEF_SafetyCarContainerV1_tags_1[0]), /* 1 */
	asn_DEF_SafetyCarContainerV1_tags_1,	/* Same as above */
	sizeof(asn_DEF_SafetyCarContainerV1_tags_1)
		/sizeof(asn_DEF_SafetyCarContainerV1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SafetyCarContainerV1_1,
	4,	/* Elements count */
	&asn_SPC_SafetyCarContainerV1_specs_1	/* Additional specs */
};

