/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "../IVIM-ASN1-files/asn1_IS_ISO_TS_14906_EfcDsrcApplication.asn"
 * 	`asn1c -fcompound-names`
 */

#ifndef	_SetStampedRq_H_
#define	_SetStampedRq_H_


#include "asn_application.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif	/* _SetStampedRq_H_ */
#include "asn_internal.h"
