/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SignalViolationSubCauseCodeV1_H_
#define	_SignalViolationSubCauseCodeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SignalViolationSubCauseCodeV1 {
	SignalViolationSubCauseCodeV1_unavailable	= 0,
	SignalViolationSubCauseCodeV1_stopSignViolation	= 1,
	SignalViolationSubCauseCodeV1_trafficLightViolation	= 2,
	SignalViolationSubCauseCodeV1_turningRegulationViolation	= 3
} e_SignalViolationSubCauseCodeV1;

/* SignalViolationSubCauseCodeV1 */
typedef long	 SignalViolationSubCauseCodeV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SignalViolationSubCauseCodeV1;
asn_struct_free_f SignalViolationSubCauseCodeV1_free;
asn_struct_print_f SignalViolationSubCauseCodeV1_print;
asn_constr_check_f SignalViolationSubCauseCodeV1_constraint;
ber_type_decoder_f SignalViolationSubCauseCodeV1_decode_ber;
der_type_encoder_f SignalViolationSubCauseCodeV1_encode_der;
xer_type_decoder_f SignalViolationSubCauseCodeV1_decode_xer;
xer_type_encoder_f SignalViolationSubCauseCodeV1_encode_xer;
oer_type_decoder_f SignalViolationSubCauseCodeV1_decode_oer;
oer_type_encoder_f SignalViolationSubCauseCodeV1_encode_oer;
per_type_decoder_f SignalViolationSubCauseCodeV1_decode_uper;
per_type_encoder_f SignalViolationSubCauseCodeV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SignalViolationSubCauseCodeV1_H_ */
#include "asn_internal.h"
