/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_StationTypeV1_H_
#define	_StationTypeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum StationTypeV1 {
	StationTypeV1_unknown	= 0,
	StationTypeV1_pedestrian	= 1,
	StationTypeV1_cyclist	= 2,
	StationTypeV1_moped	= 3,
	StationTypeV1_motorcycle	= 4,
	StationTypeV1_passengerCar	= 5,
	StationTypeV1_bus	= 6,
	StationTypeV1_lightTruck	= 7,
	StationTypeV1_heavyTruck	= 8,
	StationTypeV1_trailer	= 9,
	StationTypeV1_specialVehicles	= 10,
	StationTypeV1_tram	= 11,
	StationTypeV1_roadSideUnit	= 15
} e_StationTypeV1;

/* StationTypeV1 */
typedef long	 StationTypeV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_StationTypeV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_StationTypeV1;
asn_struct_free_f StationTypeV1_free;
asn_struct_print_f StationTypeV1_print;
asn_constr_check_f StationTypeV1_constraint;
ber_type_decoder_f StationTypeV1_decode_ber;
der_type_encoder_f StationTypeV1_encode_der;
xer_type_decoder_f StationTypeV1_decode_xer;
xer_type_encoder_f StationTypeV1_encode_xer;
oer_type_decoder_f StationTypeV1_decode_oer;
oer_type_encoder_f StationTypeV1_encode_oer;
per_type_decoder_f StationTypeV1_decode_uper;
per_type_encoder_f StationTypeV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _StationTypeV1_H_ */
#include "asn_internal.h"
