/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_SteeringWheelAngleValueV1_H_
#define	_SteeringWheelAngleValueV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SteeringWheelAngleValueV1 {
	SteeringWheelAngleValueV1_straight	= 0,
	SteeringWheelAngleValueV1_onePointFiveDegreesToRight	= -1,
	SteeringWheelAngleValueV1_onePointFiveDegreesToLeft	= 1,
	SteeringWheelAngleValueV1_unavailable	= 512
} e_SteeringWheelAngleValueV1;

/* SteeringWheelAngleValueV1 */
typedef long	 SteeringWheelAngleValueV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SteeringWheelAngleValueV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SteeringWheelAngleValueV1;
asn_struct_free_f SteeringWheelAngleValueV1_free;
asn_struct_print_f SteeringWheelAngleValueV1_print;
asn_constr_check_f SteeringWheelAngleValueV1_constraint;
ber_type_decoder_f SteeringWheelAngleValueV1_decode_ber;
der_type_encoder_f SteeringWheelAngleValueV1_encode_der;
xer_type_decoder_f SteeringWheelAngleValueV1_decode_xer;
xer_type_encoder_f SteeringWheelAngleValueV1_encode_xer;
oer_type_decoder_f SteeringWheelAngleValueV1_decode_oer;
oer_type_encoder_f SteeringWheelAngleValueV1_encode_oer;
per_type_decoder_f SteeringWheelAngleValueV1_decode_uper;
per_type_encoder_f SteeringWheelAngleValueV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _SteeringWheelAngleValueV1_H_ */
#include "asn_internal.h"
