/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ETSI-ITS-CDD"
 * 	found in "ETSI-ITS-CDD.asn"
 */

#ifndef	_TurningDirection_H_
#define	_TurningDirection_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TurningDirection {
	TurningDirection_left	= 0,
	TurningDirection_right	= 1
} e_TurningDirection;

/* TurningDirection */
typedef long	 TurningDirection_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TurningDirection_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TurningDirection;
extern const asn_INTEGER_specifics_t asn_SPC_TurningDirection_specs_1;
asn_struct_free_f TurningDirection_free;
asn_struct_print_f TurningDirection_print;
asn_constr_check_f TurningDirection_constraint;
ber_type_decoder_f TurningDirection_decode_ber;
der_type_encoder_f TurningDirection_encode_der;
xer_type_decoder_f TurningDirection_decode_xer;
xer_type_encoder_f TurningDirection_encode_xer;
oer_type_decoder_f TurningDirection_decode_oer;
oer_type_encoder_f TurningDirection_encode_oer;
per_type_decoder_f TurningDirection_decode_uper;
per_type_encoder_f TurningDirection_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TurningDirection_H_ */
#include "asn_internal.h"
