/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_ValidityDurationV1_H_
#define	_ValidityDurationV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ValidityDurationV1 {
	ValidityDurationV1_timeOfDetection	= 0,
	ValidityDurationV1_oneSecondAfterDetection	= 1
} e_ValidityDurationV1;

/* ValidityDurationV1 */
typedef long	 ValidityDurationV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ValidityDurationV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ValidityDurationV1;
asn_struct_free_f ValidityDurationV1_free;
asn_struct_print_f ValidityDurationV1_print;
asn_constr_check_f ValidityDurationV1_constraint;
ber_type_decoder_f ValidityDurationV1_decode_ber;
der_type_encoder_f ValidityDurationV1_encode_der;
xer_type_decoder_f ValidityDurationV1_decode_xer;
xer_type_encoder_f ValidityDurationV1_encode_xer;
oer_type_decoder_f ValidityDurationV1_decode_oer;
oer_type_encoder_f ValidityDurationV1_encode_oer;
per_type_decoder_f ValidityDurationV1_decode_uper;
per_type_encoder_f ValidityDurationV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _ValidityDurationV1_H_ */
#include "asn_internal.h"
