/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example -R`
 */

#ifndef	_VehicleLengthV1_H_
#define	_VehicleLengthV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VehicleLengthValueV1.h"
#include "VehicleLengthConfidenceIndicationV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleLengthV1 */
typedef struct VehicleLengthV1 {
	VehicleLengthValueV1_t	 vehicleLengthValue;
	VehicleLengthConfidenceIndicationV1_t	 vehicleLengthConfidenceIndication;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleLengthV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleLengthV1;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleLengthV1_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleLengthV1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleLengthV1_H_ */
#include "asn_internal.h"
