# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('v2i-lte-sandbox', ['automotive', 'lte', 'netanim', 'traci'])
    obj.source = 'v2i-lte-sandbox.cc'    

