/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_AltitudeConfidenceV1_H_
#define	_AltitudeConfidenceV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum AltitudeConfidenceV1 {
	AltitudeConfidenceV1_alt_000_01	= 0,
	AltitudeConfidenceV1_alt_000_02	= 1,
	AltitudeConfidenceV1_alt_000_05	= 2,
	AltitudeConfidenceV1_alt_000_10	= 3,
	AltitudeConfidenceV1_alt_000_20	= 4,
	AltitudeConfidenceV1_alt_000_50	= 5,
	AltitudeConfidenceV1_alt_001_00	= 6,
	AltitudeConfidenceV1_alt_002_00	= 7,
	AltitudeConfidenceV1_alt_005_00	= 8,
	AltitudeConfidenceV1_alt_010_00	= 9,
	AltitudeConfidenceV1_alt_020_00	= 10,
	AltitudeConfidenceV1_alt_050_00	= 11,
	AltitudeConfidenceV1_alt_100_00	= 12,
	AltitudeConfidenceV1_alt_200_00	= 13,
	AltitudeConfidenceV1_outOfRange	= 14,
	AltitudeConfidenceV1_unavailable	= 15
} e_AltitudeConfidenceV1;

/* AltitudeConfidenceV1 */
typedef long	 AltitudeConfidenceV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_AltitudeConfidenceV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_AltitudeConfidenceV1;
extern const asn_INTEGER_specifics_t asn_SPC_AltitudeConfidenceV1_specs_1;
asn_struct_free_f AltitudeConfidenceV1_free;
asn_struct_print_f AltitudeConfidenceV1_print;
asn_constr_check_f AltitudeConfidenceV1_constraint;
ber_type_decoder_f AltitudeConfidenceV1_decode_ber;
der_type_encoder_f AltitudeConfidenceV1_encode_der;
xer_type_decoder_f AltitudeConfidenceV1_decode_xer;
xer_type_encoder_f AltitudeConfidenceV1_encode_xer;
oer_type_decoder_f AltitudeConfidenceV1_decode_oer;
oer_type_encoder_f AltitudeConfidenceV1_encode_oer;
per_type_decoder_f AltitudeConfidenceV1_decode_uper;
per_type_encoder_f AltitudeConfidenceV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _AltitudeConfidenceV1_H_ */
#include "asn_internal.h"
