/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_AreaRadialV1_H_
#define	_AreaRadialV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RangeV1.h"
#include "WGS84AngleValueV1.h"
#include "CartesianAngleValueV1.h"
#include "SensorHeightV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct OffsetPointV1;

/* AreaRadialV1 */
typedef struct AreaRadialV1 {
	RangeV1_t	 range;
	WGS84AngleValueV1_t	 stationaryHorizontalOpeningAngleStart;
	WGS84AngleValueV1_t	 stationaryHorizontalOpeningAngleEnd;
	CartesianAngleValueV1_t	*verticalOpeningAngleStart;	/* OPTIONAL */
	CartesianAngleValueV1_t	*verticalOpeningAngleEnd;	/* OPTIONAL */
	struct OffsetPointV1	*sensorPositionOffset;	/* OPTIONAL */
	SensorHeightV1_t	*sensorHeight;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} AreaRadialV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_AreaRadialV1;
extern asn_SEQUENCE_specifics_t asn_SPC_AreaRadialV1_specs_1;
extern asn_TYPE_member_t asn_MBR_AreaRadialV1_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "OffsetPointV1.h"

#endif	/* _AreaRadialV1_H_ */
#include "asn_internal.h"
