/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-C-ITS/CAM-PDU-Descriptions-1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_BasicVehicleContainerLowFrequencyV1_H_
#define	_BasicVehicleContainerLowFrequencyV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "VehicleRoleV1.h"
#include "ExteriorLightsV1.h"
#include "PathHistoryV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* BasicVehicleContainerLowFrequencyV1 */
typedef struct BasicVehicleContainerLowFrequencyV1 {
	VehicleRoleV1_t	 vehicleRole;
	ExteriorLightsV1_t	 exteriorLights;
	PathHistoryV1_t	 pathHistory;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BasicVehicleContainerLowFrequencyV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_BasicVehicleContainerLowFrequencyV1;
extern asn_SEQUENCE_specifics_t asn_SPC_BasicVehicleContainerLowFrequencyV1_specs_1;
extern asn_TYPE_member_t asn_MBR_BasicVehicleContainerLowFrequencyV1_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _BasicVehicleContainerLowFrequencyV1_H_ */
#include "asn_internal.h"
