/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-C-ITS/CAM-PDU-Descriptions-1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_CamParametersV1_H_
#define	_CamParametersV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "BasicContainerV1.h"
#include "HighFrequencyContainerV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct LowFrequencyContainerV1;
struct SpecialVehicleContainerV1;

/* CamParametersV1 */
typedef struct CamParametersV1 {
	BasicContainerV1_t	 basicContainer;
	HighFrequencyContainerV1_t	 highFrequencyContainer;
	struct LowFrequencyContainerV1	*lowFrequencyContainer	/* OPTIONAL */;
	struct SpecialVehicleContainerV1	*specialVehicleContainer	/* OPTIONAL */;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CamParametersV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CamParametersV1;
extern asn_SEQUENCE_specifics_t asn_SPC_CamParametersV1_specs_1;
extern asn_TYPE_member_t asn_MBR_CamParametersV1_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "LowFrequencyContainerV1.h"
#include "SpecialVehicleContainerV1.h"

#endif	/* _CamParametersV1_H_ */
#include "asn_internal.h"
