/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_DangerousEndOfQueueSubCauseCodeV1_H_
#define	_DangerousEndOfQueueSubCauseCodeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DangerousEndOfQueueSubCauseCodeV1 {
	DangerousEndOfQueueSubCauseCodeV1_unavailable	= 0,
	DangerousEndOfQueueSubCauseCodeV1_suddenEndOfQueue	= 1,
	DangerousEndOfQueueSubCauseCodeV1_queueOverHill	= 2,
	DangerousEndOfQueueSubCauseCodeV1_queueAroundBend	= 3,
	DangerousEndOfQueueSubCauseCodeV1_queueInTunnel	= 4
} e_DangerousEndOfQueueSubCauseCodeV1;

/* DangerousEndOfQueueSubCauseCodeV1 */
typedef long	 DangerousEndOfQueueSubCauseCodeV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DangerousEndOfQueueSubCauseCodeV1;
asn_struct_free_f DangerousEndOfQueueSubCauseCodeV1_free;
asn_struct_print_f DangerousEndOfQueueSubCauseCodeV1_print;
asn_constr_check_f DangerousEndOfQueueSubCauseCodeV1_constraint;
ber_type_decoder_f DangerousEndOfQueueSubCauseCodeV1_decode_ber;
der_type_encoder_f DangerousEndOfQueueSubCauseCodeV1_encode_der;
xer_type_decoder_f DangerousEndOfQueueSubCauseCodeV1_decode_xer;
xer_type_encoder_f DangerousEndOfQueueSubCauseCodeV1_encode_xer;
oer_type_decoder_f DangerousEndOfQueueSubCauseCodeV1_decode_oer;
oer_type_encoder_f DangerousEndOfQueueSubCauseCodeV1_encode_oer;
per_type_decoder_f DangerousEndOfQueueSubCauseCodeV1_decode_uper;
per_type_encoder_f DangerousEndOfQueueSubCauseCodeV1_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _DangerousEndOfQueueSubCauseCodeV1_H_ */
#include "asn_internal.h"
