/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-C-ITS/DENM-PDU-Descriptions-1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "DecentralizedEnvironmentalNotificationMessageV1.h"

asn_TYPE_member_t asn_MBR_DecentralizedEnvironmentalNotificationMessageV1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DecentralizedEnvironmentalNotificationMessageV1, management),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ManagementContainerV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"management"
		},
	{ ATF_POINTER, 3, offsetof(struct DecentralizedEnvironmentalNotificationMessageV1, situation),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SituationContainerV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"situation"
		},
	{ ATF_POINTER, 2, offsetof(struct DecentralizedEnvironmentalNotificationMessageV1, location),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocationContainerV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"location"
		},
	{ ATF_POINTER, 1, offsetof(struct DecentralizedEnvironmentalNotificationMessageV1, alacarte),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AlacarteContainerV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"alacarte"
		},
};
static const int asn_MAP_DecentralizedEnvironmentalNotificationMessageV1_oms_1[] = { 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_DecentralizedEnvironmentalNotificationMessageV1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DecentralizedEnvironmentalNotificationMessageV1_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* management */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* situation */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* location */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* alacarte */
};
asn_SEQUENCE_specifics_t asn_SPC_DecentralizedEnvironmentalNotificationMessageV1_specs_1 = {
	sizeof(struct DecentralizedEnvironmentalNotificationMessageV1),
	offsetof(struct DecentralizedEnvironmentalNotificationMessageV1, _asn_ctx),
	asn_MAP_DecentralizedEnvironmentalNotificationMessageV1_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_DecentralizedEnvironmentalNotificationMessageV1_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DecentralizedEnvironmentalNotificationMessageV1 = {
	"DecentralizedEnvironmentalNotificationMessageV1",
	"DecentralizedEnvironmentalNotificationMessageV1",
	&asn_OP_SEQUENCE,
	asn_DEF_DecentralizedEnvironmentalNotificationMessageV1_tags_1,
	sizeof(asn_DEF_DecentralizedEnvironmentalNotificationMessageV1_tags_1)
		/sizeof(asn_DEF_DecentralizedEnvironmentalNotificationMessageV1_tags_1[0]), /* 1 */
	asn_DEF_DecentralizedEnvironmentalNotificationMessageV1_tags_1,	/* Same as above */
	sizeof(asn_DEF_DecentralizedEnvironmentalNotificationMessageV1_tags_1)
		/sizeof(asn_DEF_DecentralizedEnvironmentalNotificationMessageV1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DecentralizedEnvironmentalNotificationMessageV1_1,
	4,	/* Elements count */
	&asn_SPC_DecentralizedEnvironmentalNotificationMessageV1_specs_1	/* Additional specs */
};

