/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DENM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-C-ITS/DENM-PDU-Descriptions-1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "ManagementContainerV1.h"

static int asn_DFL_9_cmp_600(const void *sptr) {
	const ValidityDurationV1_t *st = sptr;
	
	if(!st) {
		return -1; /* No value is not a default value */
	}
	
	/* Test default value 600 */
	return (*st != 600);
}
static int asn_DFL_9_set_600(void **sptr) {
	ValidityDurationV1_t *st = *sptr;
	
	if(!st) {
		st = (*sptr = CALLOC(1, sizeof(*st)));
		if(!st) return -1;
	}
	
	/* Install default value 600 */
	*st = 600;
	return 0;
}
asn_TYPE_member_t asn_MBR_ManagementContainerV1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ManagementContainerV1, actionID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ActionIDV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"actionID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManagementContainerV1, detectionTime),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimestampItsV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"detectionTime"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManagementContainerV1, referenceTime),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TimestampItsV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"referenceTime"
		},
	{ ATF_POINTER, 1, offsetof(struct ManagementContainerV1, termination),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TerminationV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"termination"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManagementContainerV1, eventPosition),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ReferencePositionV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"eventPosition"
		},
	{ ATF_POINTER, 4, offsetof(struct ManagementContainerV1, relevanceDistance),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RelevanceDistanceV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"relevanceDistance"
		},
	{ ATF_POINTER, 3, offsetof(struct ManagementContainerV1, relevanceTrafficDirection),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RelevanceTrafficDirectionV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"relevanceTrafficDirection"
		},
	{ ATF_POINTER, 2, offsetof(struct ManagementContainerV1, validityDuration),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ValidityDurationV1,
		0,
		{ 0, 0, 0 },
		&asn_DFL_9_cmp_600,	/* Compare DEFAULT 600 */
		&asn_DFL_9_set_600,	/* Set DEFAULT 600 */
		"validityDuration"
		},
	{ ATF_POINTER, 1, offsetof(struct ManagementContainerV1, transmissionInterval),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TransmissionIntervalV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transmissionInterval"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ManagementContainerV1, stationType),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_StationTypeV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"stationType"
		},
};
static const int asn_MAP_ManagementContainerV1_oms_1[] = { 3, 5, 6, 7, 8 };
static const ber_tlv_tag_t asn_DEF_ManagementContainerV1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_ManagementContainerV1_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* actionID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* detectionTime */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* referenceTime */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* termination */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* eventPosition */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* relevanceDistance */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* relevanceTrafficDirection */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* validityDuration */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* transmissionInterval */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 } /* stationType */
};
asn_SEQUENCE_specifics_t asn_SPC_ManagementContainerV1_specs_1 = {
	sizeof(struct ManagementContainerV1),
	offsetof(struct ManagementContainerV1, _asn_ctx),
	asn_MAP_ManagementContainerV1_tag2el_1,
	10,	/* Count of tags in the map */
	asn_MAP_ManagementContainerV1_oms_1,	/* Optional members */
	5, 0,	/* Root/Additions */
	10,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_ManagementContainerV1 = {
	"ManagementContainerV1",
	"ManagementContainerV1",
	&asn_OP_SEQUENCE,
	asn_DEF_ManagementContainerV1_tags_1,
	sizeof(asn_DEF_ManagementContainerV1_tags_1)
		/sizeof(asn_DEF_ManagementContainerV1_tags_1[0]), /* 1 */
	asn_DEF_ManagementContainerV1_tags_1,	/* Same as above */
	sizeof(asn_DEF_ManagementContainerV1_tags_1)
		/sizeof(asn_DEF_ManagementContainerV1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_ManagementContainerV1_1,
	10,	/* Elements count */
	&asn_SPC_ManagementContainerV1_specs_1	/* Additional specs */
};

