/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ObjectRefPointV1_H_
#define	_ObjectRefPointV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ObjectRefPointV1 {
	ObjectRefPointV1_mid	= 0,
	ObjectRefPointV1_bottomLeft	= 1,
	ObjectRefPointV1_midLeft	= 2,
	ObjectRefPointV1_topLeft	= 3,
	ObjectRefPointV1_bottomMid	= 4,
	ObjectRefPointV1_topMid	= 5,
	ObjectRefPointV1_bottomRight	= 6,
	ObjectRefPointV1_midRight	= 7,
	ObjectRefPointV1_topRight	= 8
} e_ObjectRefPointV1;

/* ObjectRefPointV1 */
typedef long	 ObjectRefPointV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ObjectRefPointV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ObjectRefPointV1;
asn_struct_free_f ObjectRefPointV1_free;
asn_struct_print_f ObjectRefPointV1_print;
asn_constr_check_f ObjectRefPointV1_constraint;
ber_type_decoder_f ObjectRefPointV1_decode_ber;
der_type_encoder_f ObjectRefPointV1_encode_der;
xer_type_decoder_f ObjectRefPointV1_decode_xer;
xer_type_encoder_f ObjectRefPointV1_encode_xer;
oer_type_decoder_f ObjectRefPointV1_decode_oer;
oer_type_encoder_f ObjectRefPointV1_encode_oer;
per_type_decoder_f ObjectRefPointV1_decode_uper;
per_type_encoder_f ObjectRefPointV1_encode_uper;
per_type_decoder_f ObjectRefPointV1_decode_aper;
per_type_encoder_f ObjectRefPointV1_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectRefPointV1_H_ */
#include "asn_internal.h"
