/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ObjectDimensionConfidenceV1_H_
#define	_ObjectDimensionConfidenceV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ObjectDimensionConfidenceV1 {
	ObjectDimensionConfidenceV1_zeroPointZeroOneMeter	= 1,
	ObjectDimensionConfidenceV1_oneMeter	= 100,
	ObjectDimensionConfidenceV1_outOfRange	= 101,
	ObjectDimensionConfidenceV1_unavailable	= 102
} e_ObjectDimensionConfidenceV1;

/* ObjectDimensionConfidenceV1 */
typedef long	 ObjectDimensionConfidenceV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ObjectDimensionConfidenceV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ObjectDimensionConfidenceV1;
asn_struct_free_f ObjectDimensionConfidenceV1_free;
asn_struct_print_f ObjectDimensionConfidenceV1_print;
asn_constr_check_f ObjectDimensionConfidenceV1_constraint;
ber_type_decoder_f ObjectDimensionConfidenceV1_decode_ber;
der_type_encoder_f ObjectDimensionConfidenceV1_encode_der;
xer_type_decoder_f ObjectDimensionConfidenceV1_decode_xer;
xer_type_encoder_f ObjectDimensionConfidenceV1_encode_xer;
oer_type_decoder_f ObjectDimensionConfidenceV1_decode_oer;
oer_type_encoder_f ObjectDimensionConfidenceV1_encode_oer;
per_type_decoder_f ObjectDimensionConfidenceV1_decode_uper;
per_type_encoder_f ObjectDimensionConfidenceV1_encode_uper;
per_type_decoder_f ObjectDimensionConfidenceV1_decode_aper;
per_type_encoder_f ObjectDimensionConfidenceV1_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ObjectDimensionConfidenceV1_H_ */
#include "asn_internal.h"
