/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PathPointV1_H_
#define	_PathPointV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DeltaReferencePositionV1.h"
#include "PathDeltaTimeV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* PathPointV1 */
typedef struct PathPointV1 {
	DeltaReferencePositionV1_t	 pathPosition;
	PathDeltaTimeV1_t	*pathDeltaTime	/* OPTIONAL */;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PathPointV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PathPointV1;
extern asn_SEQUENCE_specifics_t asn_SPC_PathPointV1_specs_1;
extern asn_TYPE_member_t asn_MBR_PathPointV1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _PathPointV1_H_ */
#include "asn_internal.h"
