/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_CollectivePerceptionMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_AccelerationControl;
extern struct asn_TYPE_descriptor_s asn_DEF_AirHumidity;
extern struct asn_TYPE_descriptor_s asn_DEF_AxlesCount;
extern struct asn_TYPE_descriptor_s asn_DEF_BarometricPressure;
extern struct asn_TYPE_descriptor_s asn_DEF_BogiesCount;
extern struct asn_TYPE_descriptor_s asn_DEF_CenDsrcTollingZoneID;
extern struct asn_TYPE_descriptor_s asn_DEF_CurvatureCalculationMode;
extern struct asn_TYPE_descriptor_s asn_DEF_DeltaTimeMilliSecondPositive;
extern struct asn_TYPE_descriptor_s asn_DEF_DeltaTimeSecond;
extern struct asn_TYPE_descriptor_s asn_DEF_Direction;
extern struct asn_TYPE_descriptor_s asn_DEF_DriveDirection;
extern struct asn_TYPE_descriptor_s asn_DEF_EmbarkationStatus;
extern struct asn_TYPE_descriptor_s asn_DEF_EmergencyPriority;
extern struct asn_TYPE_descriptor_s asn_DEF_EnergyStorageType;
extern struct asn_TYPE_descriptor_s asn_DEF_GenerationDeltaTime;
extern struct asn_TYPE_descriptor_s asn_DEF_HeightLonCarr;
extern struct asn_TYPE_descriptor_s asn_DEF_Iso3833VehicleType;
extern struct asn_TYPE_descriptor_s asn_DEF_LaneWidth;
extern struct asn_TYPE_descriptor_s asn_DEF_LightBarSirenInUse;
extern struct asn_TYPE_descriptor_s asn_DEF_NumberOfOccupants;
extern struct asn_TYPE_descriptor_s asn_DEF_ObjectFace;
extern struct asn_TYPE_descriptor_s asn_DEF_OpeningDaysHours;
extern struct asn_TYPE_descriptor_s asn_DEF_PerformanceClass;
extern struct asn_TYPE_descriptor_s asn_DEF_PosCentMass;
extern struct asn_TYPE_descriptor_s asn_DEF_PositioningSolutionType;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionOfOccupants;
extern struct asn_TYPE_descriptor_s asn_DEF_PosFrontAx;
extern struct asn_TYPE_descriptor_s asn_DEF_PosLonCarr;
extern struct asn_TYPE_descriptor_s asn_DEF_PrecipitationIntensity;
extern struct asn_TYPE_descriptor_s asn_DEF_RelevanceDistance;
extern struct asn_TYPE_descriptor_s asn_DEF_RelevanceTrafficDirection;
extern struct asn_TYPE_descriptor_s asn_DEF_RequestResponseIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_RoadType;
extern struct asn_TYPE_descriptor_s asn_DEF_SpecialTransportType;
extern struct asn_TYPE_descriptor_s asn_DEF_SpeedLimit;
extern struct asn_TYPE_descriptor_s asn_DEF_StandardLength3b;
extern struct asn_TYPE_descriptor_s asn_DEF_StandardLength9b;
extern struct asn_TYPE_descriptor_s asn_DEF_StandardLength2B;
extern struct asn_TYPE_descriptor_s asn_DEF_StationarySince;
extern struct asn_TYPE_descriptor_s asn_DEF_Temperature;
extern struct asn_TYPE_descriptor_s asn_DEF_TrafficDirection;
extern struct asn_TYPE_descriptor_s asn_DEF_TrafficRule;
extern struct asn_TYPE_descriptor_s asn_DEF_TransmissionInterval;
extern struct asn_TYPE_descriptor_s asn_DEF_TurningRadius;
extern struct asn_TYPE_descriptor_s asn_DEF_ValidityDuration;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleHeight;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleMass;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleRole;
extern struct asn_TYPE_descriptor_s asn_DEF_VruDeviceUsage;
extern struct asn_TYPE_descriptor_s asn_DEF_VruEnvironment;
extern struct asn_TYPE_descriptor_s asn_DEF_VruMovementControl;
extern struct asn_TYPE_descriptor_s asn_DEF_VruSizeClass;
extern struct asn_TYPE_descriptor_s asn_DEF_WheelBaseVehicle;
extern struct asn_TYPE_descriptor_s asn_DEF_AccelerationChangeIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_ActionID;
extern struct asn_TYPE_descriptor_s asn_DEF_ActionIdList;
extern struct asn_TYPE_descriptor_s asn_DEF_BasicContainer;
extern struct asn_TYPE_descriptor_s asn_DEF_CartesianAngularAccelerationComponent;
extern struct asn_TYPE_descriptor_s asn_DEF_CauseCode;
extern struct asn_TYPE_descriptor_s asn_DEF_CauseCodeV2;
extern struct asn_TYPE_descriptor_s asn_DEF_CenDsrcTollingZone;
extern struct asn_TYPE_descriptor_s asn_DEF_ClosedLanes;
extern struct asn_TYPE_descriptor_s asn_DEF_ClusterBreakupInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_ClusterJoinInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_ClusterLeaveInfo;
extern struct asn_TYPE_descriptor_s asn_DEF_Curvature;
extern struct asn_TYPE_descriptor_s asn_DEF_DangerousGoodsExtended;
extern struct asn_TYPE_descriptor_s asn_DEF_DigitalMap;
extern struct asn_TYPE_descriptor_s asn_DEF_EuVehicleCategoryCode;
extern struct asn_TYPE_descriptor_s asn_DEF_EventZone;
extern struct asn_TYPE_descriptor_s asn_DEF_GeneralizedLanePosition;
extern struct asn_TYPE_descriptor_s asn_DEF_Heading;
extern struct asn_TYPE_descriptor_s asn_DEF_HeadingChangeIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_InterferenceManagementZones;
extern struct asn_TYPE_descriptor_s asn_DEF_ItineraryPath;
extern struct asn_TYPE_descriptor_s asn_DEF_LateralAcceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_LongitudinalAcceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_PathHistory;
extern struct asn_TYPE_descriptor_s asn_DEF_PathPredicted;
extern struct asn_TYPE_descriptor_s asn_DEF_PositionOfPillars;
extern struct asn_TYPE_descriptor_s asn_DEF_ProtectedCommunicationZonesRSU;
extern struct asn_TYPE_descriptor_s asn_DEF_PtActivation;
extern struct asn_TYPE_descriptor_s asn_DEF_RestrictedTypes;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfSafeDistanceIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_SequenceOfTrajectoryInterceptionIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_StabilityChangeIndication;
extern struct asn_TYPE_descriptor_s asn_DEF_SteeringWheelAngle;
extern struct asn_TYPE_descriptor_s asn_DEF_Traces;
extern struct asn_TYPE_descriptor_s asn_DEF_VarLengthNumber;
extern struct asn_TYPE_descriptor_s asn_DEF_VerticalAcceleration;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleIdentification;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleLength;
extern struct asn_TYPE_descriptor_s asn_DEF_VehicleLengthV2;
extern struct asn_TYPE_descriptor_s asn_DEF_VruExteriorLights;
extern struct asn_TYPE_descriptor_s asn_DEF_YawRate;
extern struct asn_TYPE_descriptor_s asn_DEF_EXTERNAL;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module CPM-PDU-Descriptions in CPM-all.asn */
	&asn_DEF_CollectivePerceptionMessage,	
	/* From module ETSI-ITS-CDD in CPM-all.asn */
	&asn_DEF_AccelerationControl,	
	&asn_DEF_AirHumidity,	
	&asn_DEF_AxlesCount,	
	&asn_DEF_BarometricPressure,	
	&asn_DEF_BogiesCount,	
	&asn_DEF_CenDsrcTollingZoneID,	
	&asn_DEF_CurvatureCalculationMode,	
	&asn_DEF_DeltaTimeMilliSecondPositive,	
	&asn_DEF_DeltaTimeSecond,	
	&asn_DEF_Direction,	
	&asn_DEF_DriveDirection,	
	&asn_DEF_EmbarkationStatus,	
	&asn_DEF_EmergencyPriority,	
	&asn_DEF_EnergyStorageType,	
	&asn_DEF_GenerationDeltaTime,	
	&asn_DEF_HeightLonCarr,	
	&asn_DEF_Iso3833VehicleType,	
	&asn_DEF_LaneWidth,	
	&asn_DEF_LightBarSirenInUse,	
	&asn_DEF_NumberOfOccupants,	
	&asn_DEF_ObjectFace,	
	&asn_DEF_OpeningDaysHours,	
	&asn_DEF_PerformanceClass,	
	&asn_DEF_PosCentMass,	
	&asn_DEF_PositioningSolutionType,	
	&asn_DEF_PositionOfOccupants,	
	&asn_DEF_PosFrontAx,	
	&asn_DEF_PosLonCarr,	
	&asn_DEF_PrecipitationIntensity,	
	&asn_DEF_RelevanceDistance,	
	&asn_DEF_RelevanceTrafficDirection,	
	&asn_DEF_RequestResponseIndication,	
	&asn_DEF_RoadType,	
	&asn_DEF_SpecialTransportType,	
	&asn_DEF_SpeedLimit,	
	&asn_DEF_StandardLength3b,	
	&asn_DEF_StandardLength9b,	
	&asn_DEF_StandardLength2B,	
	&asn_DEF_StationarySince,	
	&asn_DEF_Temperature,	
	&asn_DEF_TrafficDirection,	
	&asn_DEF_TrafficRule,	
	&asn_DEF_TransmissionInterval,	
	&asn_DEF_TurningRadius,	
	&asn_DEF_ValidityDuration,	
	&asn_DEF_VehicleHeight,	
	&asn_DEF_VehicleMass,	
	&asn_DEF_VehicleRole,	
	&asn_DEF_VruDeviceUsage,	
	&asn_DEF_VruEnvironment,	
	&asn_DEF_VruMovementControl,	
	&asn_DEF_VruSizeClass,	
	&asn_DEF_WheelBaseVehicle,	
	&asn_DEF_AccelerationChangeIndication,	
	&asn_DEF_ActionID,	
	&asn_DEF_ActionIdList,	
	&asn_DEF_BasicContainer,	
	&asn_DEF_CartesianAngularAccelerationComponent,	
	&asn_DEF_CauseCode,	
	&asn_DEF_CauseCodeV2,	
	&asn_DEF_CenDsrcTollingZone,	
	&asn_DEF_ClosedLanes,	
	&asn_DEF_ClusterBreakupInfo,	
	&asn_DEF_ClusterJoinInfo,	
	&asn_DEF_ClusterLeaveInfo,	
	&asn_DEF_Curvature,	
	&asn_DEF_DangerousGoodsExtended,	
	&asn_DEF_DigitalMap,	
	&asn_DEF_EuVehicleCategoryCode,	
	&asn_DEF_EventZone,	
	&asn_DEF_GeneralizedLanePosition,	
	&asn_DEF_Heading,	
	&asn_DEF_HeadingChangeIndication,	
	&asn_DEF_InterferenceManagementZones,	
	&asn_DEF_ItineraryPath,	
	&asn_DEF_LateralAcceleration,	
	&asn_DEF_LongitudinalAcceleration,	
	&asn_DEF_PathHistory,	
	&asn_DEF_PathPredicted,	
	&asn_DEF_PositionOfPillars,	
	&asn_DEF_ProtectedCommunicationZonesRSU,	
	&asn_DEF_PtActivation,	
	&asn_DEF_RestrictedTypes,	
	&asn_DEF_SequenceOfSafeDistanceIndication,	
	&asn_DEF_SequenceOfTrajectoryInterceptionIndication,	
	&asn_DEF_StabilityChangeIndication,	
	&asn_DEF_SteeringWheelAngle,	
	&asn_DEF_Traces,	
	&asn_DEF_VarLengthNumber,	
	&asn_DEF_VerticalAcceleration,	
	&asn_DEF_VehicleIdentification,	
	&asn_DEF_VehicleLength,	
	&asn_DEF_VehicleLengthV2,	
	&asn_DEF_VruExteriorLights,	
	&asn_DEF_YawRate,	
	/* From module ASN1C-UsefulInformationObjectClasses in /usr/local/share/asn1c/standard-modules/ASN1C-UsefulInformationObjectClasses.asn1 */
	&asn_DEF_EXTERNAL,	
	0
};

