/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_PerceivedObjectContainerV1_H_
#define	_PerceivedObjectContainerV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct PerceivedObjectV1;

/* PerceivedObjectContainerV1 */
typedef struct PerceivedObjectContainerV1 {
	A_SEQUENCE_OF(struct PerceivedObjectV1) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PerceivedObjectContainerV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PerceivedObjectContainerV1;
extern asn_SET_OF_specifics_t asn_SPC_PerceivedObjectContainerV1_specs_1;
extern asn_TYPE_member_t asn_MBR_PerceivedObjectContainerV1_1[1];
extern asn_per_constraints_t asn_PER_type_PerceivedObjectContainerV1_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "PerceivedObjectV1.h"

#endif	/* _PerceivedObjectContainerV1_H_ */
#include "asn_internal.h"
