/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_ReceiptServicePart_H_
#define	_ReceiptServicePart_H_


#include "asn_application.h"

/* Including external dependencies */
#include "DateAndTime.h"
#include "Provider.h"
#include "NativeInteger.h"
#include "BIT_STRING.h"
#include "StationTypeEfc.h"
#include "ResultOp.h"
#include "ResultFin.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ReceiptServicePart */
typedef struct ReceiptServicePart {
	DateAndTime_t	 sessionTime;
	Provider_t	 sessionServiceProvider;
	long	 stationLocation;
	BIT_STRING_t	 sessionLocation;
	StationTypeEfc_t	 typeOfSession;
	ResultOp_t	 sessionResultOperational;
	ResultFin_t	 sessionResultFinancial;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ReceiptServicePart_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ReceiptServicePart;

#ifdef __cplusplus
}
#endif

#endif	/* _ReceiptServicePart_H_ */
#include "asn_internal.h"
