/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-C-ITS/CAM-PDU-Descriptions-1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_RescueContainerV1_H_
#define	_RescueContainerV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "LightBarSirenInUseV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RescueContainerV1 */
typedef struct RescueContainerV1 {
	LightBarSirenInUseV1_t	 lightBarSirenInUse;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RescueContainerV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RescueContainerV1;
extern asn_SEQUENCE_specifics_t asn_SPC_RescueContainerV1_specs_1;
extern asn_TYPE_member_t asn_MBR_RescueContainerV1_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RescueContainerV1_H_ */
#include "asn_internal.h"
