/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CAM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-C-ITS/CAM-PDU-Descriptions-1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "RoadWorksContainerBasicV1.h"

asn_TYPE_member_t asn_MBR_RoadWorksContainerBasicV1_1[] = {
	{ ATF_POINTER, 1, offsetof(struct RoadWorksContainerBasicV1, roadworksSubCauseCode),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RoadworksSubCauseCodeV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"roadworksSubCauseCode"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RoadWorksContainerBasicV1, lightBarSirenInUse),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LightBarSirenInUseV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"lightBarSirenInUse"
		},
	{ ATF_POINTER, 1, offsetof(struct RoadWorksContainerBasicV1, closedLanes),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ClosedLanesV1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"closedLanes"
		},
};
static const int asn_MAP_RoadWorksContainerBasicV1_oms_1[] = { 0, 2 };
static const ber_tlv_tag_t asn_DEF_RoadWorksContainerBasicV1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RoadWorksContainerBasicV1_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* roadworksSubCauseCode */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* lightBarSirenInUse */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* closedLanes */
};
asn_SEQUENCE_specifics_t asn_SPC_RoadWorksContainerBasicV1_specs_1 = {
	sizeof(struct RoadWorksContainerBasicV1),
	offsetof(struct RoadWorksContainerBasicV1, _asn_ctx),
	asn_MAP_RoadWorksContainerBasicV1_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_RoadWorksContainerBasicV1_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RoadWorksContainerBasicV1 = {
	"RoadWorksContainerBasicV1",
	"RoadWorksContainerBasicV1",
	&asn_OP_SEQUENCE,
	asn_DEF_RoadWorksContainerBasicV1_tags_1,
	sizeof(asn_DEF_RoadWorksContainerBasicV1_tags_1)
		/sizeof(asn_DEF_RoadWorksContainerBasicV1_tags_1[0]), /* 1 */
	asn_DEF_RoadWorksContainerBasicV1_tags_1,	/* Same as above */
	sizeof(asn_DEF_RoadWorksContainerBasicV1_tags_1)
		/sizeof(asn_DEF_RoadWorksContainerBasicV1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RoadWorksContainerBasicV1_1,
	3,	/* Elements count */
	&asn_SPC_RoadWorksContainerBasicV1_specs_1	/* Additional specs */
};

