/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SensorTypeV1_H_
#define	_SensorTypeV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SensorTypeV1 {
	SensorTypeV1_undefined	= 0,
	SensorTypeV1_radar	= 1,
	SensorTypeV1_lidar	= 2,
	SensorTypeV1_monovideo	= 3,
	SensorTypeV1_stereovision	= 4,
	SensorTypeV1_nightvision	= 5,
	SensorTypeV1_ultrasonic	= 6,
	SensorTypeV1_pmd	= 7,
	SensorTypeV1_fusion	= 8,
	SensorTypeV1_inductionloop	= 9,
	SensorTypeV1_sphericalCamera	= 10,
	SensorTypeV1_itssaggregation	= 11
} e_SensorTypeV1;

/* SensorTypeV1 */
typedef long	 SensorTypeV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SensorTypeV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SensorTypeV1;
asn_struct_free_f SensorTypeV1_free;
asn_struct_print_f SensorTypeV1_print;
asn_constr_check_f SensorTypeV1_constraint;
ber_type_decoder_f SensorTypeV1_decode_ber;
der_type_encoder_f SensorTypeV1_encode_der;
xer_type_decoder_f SensorTypeV1_decode_xer;
xer_type_encoder_f SensorTypeV1_encode_xer;
oer_type_decoder_f SensorTypeV1_decode_oer;
oer_type_encoder_f SensorTypeV1_encode_oer;
per_type_decoder_f SensorTypeV1_decode_uper;
per_type_encoder_f SensorTypeV1_encode_uper;
per_type_decoder_f SensorTypeV1_decode_aper;
per_type_encoder_f SensorTypeV1_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SensorTypeV1_H_ */
#include "asn_internal.h"
