/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#include "SessionClass.h"

static asn_TYPE_member_t asn_MBR_SessionClass_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SessionClass, sessionTariffClass),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Int1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sessionTariffClass"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SessionClass, sessionClaimedClass),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Int1,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sessionClaimedClass"
		},
};
static const ber_tlv_tag_t asn_DEF_SessionClass_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SessionClass_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sessionTariffClass */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* sessionClaimedClass */
};
static asn_SEQUENCE_specifics_t asn_SPC_SessionClass_specs_1 = {
	sizeof(struct SessionClass),
	offsetof(struct SessionClass, _asn_ctx),
	asn_MAP_SessionClass_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SessionClass = {
	"SessionClass",
	"SessionClass",
	&asn_OP_SEQUENCE,
	asn_DEF_SessionClass_tags_1,
	sizeof(asn_DEF_SessionClass_tags_1)
		/sizeof(asn_DEF_SessionClass_tags_1[0]), /* 1 */
	asn_DEF_SessionClass_tags_1,	/* Same as above */
	sizeof(asn_DEF_SessionClass_tags_1)
		/sizeof(asn_DEF_SessionClass_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SessionClass_1,
	2,	/* Elements count */
	&asn_SPC_SessionClass_specs_1	/* Additional specs */
};

