/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ITS-Container.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SpeedV1_H_
#define	_SpeedV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SpeedValueV1.h"
#include "SpeedConfidenceV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SpeedV1 */
typedef struct SpeedV1 {
	SpeedValueV1_t	 speedValue;
	SpeedConfidenceV1_t	 speedConfidence;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SpeedV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SpeedV1;
extern asn_SEQUENCE_specifics_t asn_SPC_SpeedV1_specs_1;
extern asn_TYPE_member_t asn_MBR_SpeedV1_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _SpeedV1_H_ */
#include "asn_internal.h"
