/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_SpeedValueExtendedV1_H_
#define	_SpeedValueExtendedV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SpeedValueExtendedV1 {
	SpeedValueExtendedV1_standstill	= 0,
	SpeedValueExtendedV1_oneCentimeterPerSec	= 1,
	SpeedValueExtendedV1_unavailable	= 16383
} e_SpeedValueExtendedV1;

/* SpeedValueExtendedV1 */
typedef long	 SpeedValueExtendedV1_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SpeedValueExtendedV1_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SpeedValueExtendedV1;
asn_struct_free_f SpeedValueExtendedV1_free;
asn_struct_print_f SpeedValueExtendedV1_print;
asn_constr_check_f SpeedValueExtendedV1_constraint;
ber_type_decoder_f SpeedValueExtendedV1_decode_ber;
der_type_encoder_f SpeedValueExtendedV1_encode_der;
xer_type_decoder_f SpeedValueExtendedV1_decode_xer;
xer_type_encoder_f SpeedValueExtendedV1_encode_xer;
oer_type_decoder_f SpeedValueExtendedV1_decode_oer;
oer_type_encoder_f SpeedValueExtendedV1_encode_oer;
per_type_decoder_f SpeedValueExtendedV1_decode_uper;
per_type_encoder_f SpeedValueExtendedV1_encode_uper;
per_type_decoder_f SpeedValueExtendedV1_decode_aper;
per_type_encoder_f SpeedValueExtendedV1_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SpeedValueExtendedV1_H_ */
#include "asn_internal.h"
