/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/mnt/EVO/ASN1-C-ITS/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_TractorAxles_H_
#define	_TractorAxles_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TractorAxles */
typedef long	 TractorAxles_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TractorAxles_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TractorAxles;
asn_struct_free_f TractorAxles_free;
asn_struct_print_f TractorAxles_print;
asn_constr_check_f TractorAxles_constraint;
ber_type_decoder_f TractorAxles_decode_ber;
der_type_encoder_f TractorAxles_encode_der;
xer_type_decoder_f TractorAxles_decode_xer;
xer_type_encoder_f TractorAxles_encode_xer;
oer_type_decoder_f TractorAxles_decode_oer;
oer_type_encoder_f TractorAxles_encode_oer;
per_type_decoder_f TractorAxles_decode_uper;
per_type_encoder_f TractorAxles_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TractorAxles_H_ */
#include "asn_internal.h"
