/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/mnt/EVO/ASN1-stuff/ASN1-C-ITS/CPMv1.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -no-gen-example`
 */

#ifndef	_VehicleSensorV1_H_
#define	_VehicleSensorV1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RefPointIdV1.h"
#include "XSensorOffsetV1.h"
#include "YSensorOffsetV1.h"
#include "ZSensorOffsetV1.h"
#include "VehicleSensorPropertyListV1.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleSensorV1 */
typedef struct VehicleSensorV1 {
	RefPointIdV1_t	 refPointId;	/* DEFAULT 0 */
	XSensorOffsetV1_t	 xSensorOffset;
	YSensorOffsetV1_t	 ySensorOffset;
	ZSensorOffsetV1_t	*zSensorOffset;	/* OPTIONAL */
	VehicleSensorPropertyListV1_t	 vehicleSensorPropertyList;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} VehicleSensorV1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleSensorV1;
extern asn_SEQUENCE_specifics_t asn_SPC_VehicleSensorV1_specs_1;
extern asn_TYPE_member_t asn_MBR_VehicleSensorV1_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleSensorV1_H_ */
#include "asn_internal.h"
